OGRECave/ogre

OgreMain/src/OgreMeshSerializerImpl.cpp

corrupted chunks due to the artificially enlarged position buffers

Fixed mesh serialization for meshes prepared for shadow volumes

---

OgreMain/include/OgreNode.h
OgreMain/include/OgreSceneNode.h
OgreMain/src/OgreNode.cpp
OgreMain/src/OgreSceneNode.cpp

this is safe as we are the only ones deriving from Node via SceneNode
and Bone:

Nonvirtual scene

---

OgreMain/src/OgreQuaternion.cpp
Tests/OgreMain/src/QuaternionTests.cpp

The exponential of a quaternion was incorrect, the results were different from what can be found with Matlab or Octave.
The logarithm computation is improved by using the atan2 form to compute the angle. As mentioned in "Quaternion Computation" by Neil Dantam, it is best for numerical stability.
http://www.neil.dantam.name/note/dantam-quaternion.pdf

Correction of EXP and LOG operations on Quaternions.

---

RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp

OGRE does not track the required information so the usage pattern was
wrong.

GL*: do not use glDrawRangeElements

---

RenderSystems/GL/CMakeLists.txt
RenderSystems/GL3Plus/CMakeLists.txt
RenderSystems/GLES2/CMakeLists.txt

fixes unresolved glX* symbols in GLSupport

GL*: change library order to correctly link against libGL

---

OgreMain/src/OgrePlatformInformation.cpp

android cpufeatures are not unique across architectures

PlatformInformation: Android - fix detecting NEON on x86

---

OgreMain/src/OgreDistanceLodStrategy.cpp
OgreMain/src/OgrePixelCountLodStrategy.cpp

When a mesh node is scaled the LOD strategy fail to compute the correct
distance / pixel ratio.

LOD strategy: consider derived scale of the object

---

Components/RTShaderSystem/src/OgreShaderExHardwareSkinning.cpp
OgreMain/include/OgreHardwareVertexBuffer.h
OgreMain/include/OgreMeshManager.h
OgreMain/src/OgreHardwareVertexBuffer.cpp
OgreMain/src/OgreMesh.cpp
OgreMain/src/OgreMeshManager.cpp
RenderSystems/Direct3D11/src/OgreD3D11Mappings.cpp
RenderSystems/Direct3D9/src/OgreD3D9Mappings.cpp
RenderSystems/GL/src/OgreGLHardwareBufferManager.cpp
RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusHardwareBufferManager.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/src/OgreGLES2HardwareBufferManager.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
Samples/Media/RTShaderLib/GLSL/DualQuaternionSkinning_ShadowFourWeights.glsl
Samples/Media/RTShaderLib/GLSL/DualQuaternionSkinning_ShadowOneWeight.glsl
Samples/Media/RTShaderLib/GLSL/DualQuaternionSkinning_ShadowThreeWeights.glsl
Samples/Media/RTShaderLib/GLSL/DualQuaternion_Common.glsl

original PR: https://bitbucket.org/sinbad/ogre/pull-requests/400
Allow users to opt for storing blend weights as bytes or shorts (or floats as they have been). This can reduce the vertex buffer storage for skinned meshes substantially. When using the newly added normalized vertex element types, skinning shaders can be used without changes.
Tested with DX11 and DX9.
I can't seem to find where in the GL rendersystems the mapping from VertexElementType values to GL types takes place. Perhaps someone who knows that code could handle that part.

Blend weights vertex formats

---

OgreMain/src/OgrePixelFormat.cpp

In case of PF_ETC1_RGB8, PF_ETC2_RGB8, PF_ETC2_RGBA8, PF_ETC2_RGB8A1
PixelUtil::getMemorySize() returns incorrect result.
Basically, we have mipmaps and in order to calculate whole texture size,
we need to calculate every mipmap size. Everything is ok, until we get
2x2 and 1x1. It is said in those ETC docs, that minimum block size is 8
bytes. When we calculate size for 2x2 and 1x1, we have to take that
minimum size, rather than calculated one.

[BUGFIX] Calculate ETC compressed image memory size

---

RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/include/EAGL/OgreEAGLES2Context.h
RenderSystems/GLES2/src/EAGL/OgreEAGLES2Context.mm
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
RenderSystems/GLSupport/include/OSX/OgreOSXCocoaContext.h
RenderSystems/GLSupport/include/OgreGLContext.h
RenderSystems/GLSupport/src/OSX/OgreOSXCocoaContext.mm

gl calls are supposed to be made by the RS and not by Support

GLSupport: remove barrier() - glFlush does not belong into GLContext

---

RenderSystems/GL/src/OgreGLFBORenderTexture.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusFBORenderTexture.cpp
RenderSystems/GLES2/src/OgreGLES2FBORenderTexture.cpp
RenderSystems/GLSupport/include/OgreGLRenderTexture.h
RenderSystems/GLSupport/src/OgreGLRenderTexture.cpp

from: http://www.ogre3d.org/forums/viewtopic.php?f=25&t=92915
each Ogre::Texture would have a unique resolve texture, but would share the same MSAA surface.
1. existing renderbuffers with the same format to not reused. Instead, a new renderbuffer is created with the same format, which overwrites the element in the map that might have been there prior to the call. 
2. Thus, when the original renderbuffer with the same format is supposed to be released, the new renderbuffer is found instead, and deleted. 
3. With the wrong renderbuffer deleted, the memory error occurs when a texture is deleted which refers to the incorrectly deleted renderbuffer.

Renderbuffer reuse

---

RenderSystems/GL/include/OgreGLGpuProgram.h
RenderSystems/GL/include/OgreGLRenderSystem.h
RenderSystems/GL/src/GLSL/include/OgreGLSLGpuProgram.h
RenderSystems/GL/src/GLSL/include/OgreGLSLLinkProgram.h
RenderSystems/GL/src/GLSL/src/OgreGLSLGpuProgram.cpp
RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp
RenderSystems/GL/src/OgreGLGpuProgram.cpp
RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/include/GLSL/OgreGLSLProgram.h
RenderSystems/GL3Plus/include/GLSL/OgreGLSLSeparableProgram.h
RenderSystems/GL3Plus/include/OgreGL3PlusRenderSystem.h
RenderSystems/GL3Plus/src/GLSL/OgreGLSLMonolithicProgram.cpp
RenderSystems/GL3Plus/src/GLSL/OgreGLSLProgram.cpp
RenderSystems/GL3Plus/src/GLSL/OgreGLSLSeparableProgram.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/include/OgreGLES2RenderSystem.h
RenderSystems/GLES2/src/GLSLES/include/OgreGLSLESProgramCommon.h
RenderSystems/GLES2/src/GLSLES/include/OgreGLSLESProgramPipeline.h
RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESLinkProgram.cpp
RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramCommon.cpp
RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramPipeline.cpp
RenderSystems/GLES2/src/OgreGLES2HardwarePixelBuffer.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
RenderSystems/GLSupport/include/GLSL/OgreGLSLProgramCommon.h
RenderSystems/GLSupport/include/OgreGLRenderSystemCommon.h
RenderSystems/GLSupport/include/OgreGLVertexArrayObject.h
RenderSystems/GLSupport/src/GLSL/OgreGLSLProgramCommon.cpp
RenderSystems/GLSupport/src/OgreGLVertexArrayObject.cpp

now that we have fixed and predefined attribute locations, we do not
need to query them by name. Note that even before we only queried a set
of predefined names.
Update API accordingly.

GL*: use fixed attribute indices

---

Samples/HLMS/include/HLMS.h

and drop the latter. Reducing the Media size by 50%.

HLMS: cubemap - use cubescene instead of huge SaintPetersBasilica

---

OgreMain/include/OgreString.h

Without these includes, I get this error using the default cmake generator (make) rather than with `-G Xcode`:
```
In file included from /Users/william/ogre-1.10.7/Components/Overlay/src/OgreBorderPanelOverlayElement.cpp:35:
In file included from /Users/william/ogre-1.10.7/OgreMain/include/OgreRoot.h:34:
In file included from /Users/william/ogre-1.10.7/OgreMain/include/OgreSceneManagerEnumerator.h:33:
In file included from /Users/william/ogre-1.10.7/OgreMain/include/OgreSceneManager.h:48:
In file included from /Users/william/ogre-1.10.7/OgreMain/include/OgreRenderSystem.h:37:
In file included from /Users/william/ogre-1.10.7/OgreMain/include/OgreRenderSystemCapabilities.h:34:
/Users/william/ogre-1.10.7/OgreMain/include/OgreStringConverter.h:297:10: error: unknown type name 'locale_t' …
```

add includes for locale_t when using make on macOS

---

CMake/Utils/OgreConfigTargets.cmake
Samples/Browser/CMakeLists.txt

I've replaced all PDB install hardcoded paths with the `$<TARGET_PDB_FILE:tgt>` cmake generator expression, this seems to be the _cleanest_ solution, however, this _might_ break other systems which do not support PDB files.
The generator expression (https://github.com/thedmd/cmake-hacked/blob/master/Source/cmGeneratorExpressionEvaluator.cxx#L1598) checks for PDB support in the `"CMAKE_" + language + "_LINKER_SUPPORTS_PDB"` variable, unfortunately `get_target_property(LINKER_LANGUAGE, [target], LINKER_LANGUAGE)` always returned me NOTFOUND, so I couldn't check for PDB-Support. A hardcoded `CMAKE_CXX_LINKER_SUPPORTS_PDB` might work, not sure though. (Calling the generator-expression on unsupported targets breaks the build completely, thats why we need to check manually)
Just setting …

Fix PDB installation on Win32

---

RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp

discovered on GLES2/ Emscripten

GL*: do not select packed depth-stencil if stencil is unavailable

---

RenderSystems/GLSupport/src/GLX/OgreGLXGLSupport.cpp
RenderSystems/GLSupport/src/GLX/OgreGLXWindow.cpp

I'm trying to use Ogre 1.10.7 in a Linux (Ubuntu 16.04) VM on my macbook pro. My opengl version is 2.1 and GSLS version 1.2. I've been running into segfaults because some of the glx extension functions are not being found (i.e. `glXGetProcAddressARB` is returning `nullptr`. In this pull request I'm improving detection for these functions (so you get a runtime error instead of a segfault), but I'm still not sure why these functions are not loading. I'm wondering if the 1.10 releases have been tested on opengl 2.1 very well and maybe some unavailable opengl 3+ functions are being used in the common gl support part of Ogre.
My setup is admittedly a bit exotic (doing static linking and integrating into a Qt5 QWindow), but I can follow up on why these functions are not loaded in my case in a …

check that glx extension functions are found

---

RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp

This caused the stencil buffer to be unbound when using stencil test for these formats. 
The bug was introduced at commit 369fdbbfe95b3f5b4991c6718b4e08d07b4a35d0. I'm not sure it is the best way to fix it but that looked safer than modifying getBestDepthStencil(). 
Also beware I did the modifications for all render systems but I could only test it on GL3Plus.

GL*: use depth buffer as stencil buffer pointer for packed formats

---

OgreMain/include/OgreCommon.h
OgreMain/include/OgreHardwareBuffer.h
RenderSystems/GL/src/OgreGLHardwarePixelBuffer.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusHardwarePixelBuffer.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusTextureBuffer.cpp
RenderSystems/GLES2/src/OgreGLES2HardwarePixelBuffer.cpp
RenderSystems/GLSupport/src/OgreGLHardwarePixelBufferCommon.cpp

- use copy assignment to keep the correct stride
- disable incorrect PBO upload on GLES3

GLES2: fix BlitSubTextures

---

OgreMain/src/OgreInstanceBatch.cpp

This fixes an issue where bounding boxes wouldn't be updated.

Make sure parent node is marked as dirty.

---

Components/Bites/src/OgreApplicationContext.cpp
OgreMain/src/OgreEntity.cpp
OgreMain/src/OgreMaterial.cpp
RenderSystems/GL/src/nvparse/ps1.0_program.cpp

Warnings:
- [V595](https://www.viva64.com/en/w/v595/) The 'mRoot' pointer was utilized before it was verified against nullptr. Check lines: 100, 104. [ogreapplicationcontext.cpp 100](https://github.com/OGRECave/ogre/blob/master/Components/Bites/src/OgreApplicationContext.cpp#L100)
- [V595](https://www.viva64.com/en/w/v595/) The 'mAnimationState' pointer was utilized before it was verified against nullptr. Check lines: 2005, 2020. [ogreentity.cpp 2005](https://github.com/OGRECave/ogre/blob/master/OgreMain/src/OgreEntity.cpp#L2005)
- [V595](https://www.viva64.com/en/w/v595/) The 'mLodStrategy' pointer was utilized before it was verified against nullptr. Check lines: 791, 795. …

Fix V595 warnings from PVS-Studio Static Analyzer

---

Components/Bites/src/OgreApplicationContext.cpp
OgreMain/src/OgreEdgeListBuilder.cpp
OgreMain/src/OgreEntity.cpp
OgreMain/src/OgreMaterial.cpp
RenderSystems/GL/src/nvparse/ps1.0_program.cpp

Warning:
- [V535](https://www.viva64.com/en/w/v535/) The variable 'i' is being used for this loop and for the outer loop. Check lines: 515, 594. [ogreedgelistbuilder.cpp 594](https://github.com/OGRECave/ogre/blob/master/OgreMain/src/OgreEdgeListBuilder.cpp#L594)

Fix V535 warnings from PVS-Studio Static Analyzer

---

Components/Bites/src/OgreApplicationContext.cpp
OgreMain/src/OgreEdgeListBuilder.cpp
OgreMain/src/OgreEntity.cpp
OgreMain/src/OgreMaterial.cpp
RenderSystems/Direct3D11/src/OgreD3D11MultiRenderTarget.cpp
RenderSystems/GL/src/nvparse/ps1.0_program.cpp

Warning:
- [V579](https://www.viva64.com/en/w/v579/) The memset function receives the pointer and its size as arguments. It is possibly a mistake. Inspect the third argument. [ogred3d11multirendertarget.cpp 129](https://github.com/OGRECave/ogre/blob/master/RenderSystems/Direct3D11/src/OgreD3D11MultiRenderTarget.cpp#L129)

Fix V579 warnings from PVS-Studio Static Analyzer

---

Components/Bites/src/OgreApplicationContext.cpp
OgreMain/src/OgreEdgeListBuilder.cpp
OgreMain/src/OgreEntity.cpp
OgreMain/src/OgreMaterial.cpp
RenderSystems/Direct3D11/src/OgreD3D11MultiRenderTarget.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderWindow.cpp
RenderSystems/GL/src/nvparse/ps1.0_program.cpp

Warning:
- [V501](https://www.viva64.com/en/w/v501/) There are identical sub-expressions to the left and to the right of the '!=' operator: dst.getHeight() != dst.getHeight() [ogred3d11renderwindow.cpp 321](https://github.com/OGRECave/ogre/blob/master/RenderSystems/Direct3D11/src/OgreD3D11RenderWindow.cpp#L321)

Fix V501 warnings from PVS-Studio Static Analyzer

---

Components/Bites/src/OgreApplicationContext.cpp
OgreMain/src/OgreEdgeListBuilder.cpp
OgreMain/src/OgreEntity.cpp
OgreMain/src/OgreMaterial.cpp
OgreMain/src/OgreScriptTranslator.cpp
RenderSystems/Direct3D11/src/OgreD3D11MultiRenderTarget.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderWindow.cpp
RenderSystems/GL/src/nvparse/ps1.0_program.cpp

Warning:
- [V734](https://www.viva64.com/en/w/v734/) An excessive check. Examine the conditions containing search for the substrings "int" and "uint". [ogrescripttranslator.cpp 513](https://github.com/OGRECave/ogre/blob/master/OgreMain/src/OgreScriptTranslator.cpp#L513)

Fix V734 warnings from PVS-Studio Static Analyzer

---

OgreMain/src/OgreInstanceManager.cpp

Depending on the compiler, inserting into a map while reading the size
of in the same line produces different results. So on some machines the
indices would be messed up if a mesh with shared vertex data was used.
See https://blog.jayway.com/2015/09/08/undefined-behaviour-in-c-when-adding-to-map/ for more info.

Fixed issue with indices.

---

CMake/InstallResources.cmake

I.e. sync with how CMakeLists.txt does it.
Otherwise some ends up in /usr/lib/OGRE/cmake/ and others in /usr/lib64/OGRE/cmake/.

Install all cmake files in same directory.

---

OgreMain/src/OgrePixelFormatDescriptions.h

Specify that constants are ULL.

---

Components/Terrain/include/OgreTerrainGroup.h
Components/Terrain/src/OgreTerrainGroup.cpp
OgreMain/include/OgreWorkQueue.h
OgreMain/src/OgreWorkQueue.cpp

TerrainGroup will use Terrain instance inside thread but allows destroying it while it's being processed in the thread.

OgreTerrainGroup thread safety regarding Terrain creation

---

CMake/Utils/AndroidMacros.cmake
CMakeLists.txt
Samples/Browser/CMakeLists.txt

This pull request is related to https://ogre3d.atlassian.net/browse/OGRE-568.
It adds the option `OGRE_BUILD_ANDROID_JNI_LIBS_CMAKE` which enables the building of the SampleBrowser library on android using CMake instead of android makefiles.
However this does not completely solve the referenced issue.
I tested this on a physical android device, where it worked.
Besides, it was the only way to build OGRE using the newest NDK with the Clang compiler.

Android Build SampleBrowser library using CMake instead of android makefiles

---

OgreMain/src/OgreBillboardChain.cpp

Fixes #603 
- getNumChainElements now returns 0 if chain is empty
- getChainElement throws an exception when chain is empty exhibiting the same behaviour as updateChainElement

Fix OgreBillboardChain

---

Components/RTShaderSystem/src/OgreShaderFFPTexturing.cpp

https://ogre3d.atlassian.net/browse/OGRE-592

[OGRE-592] RTShaderSystem compile error when using double precision

---

OgreMain/src/OgreETCCodec.cpp
OgreMain/src/OgrePixelFormat.cpp

This PR do essentially three things (aiming to get pvrtc to work on Metal/iOS):
- Adds support for PVRTC pixel format in the KTX-loader (named ETCCodec). KTX is a general container (similar to DDS) and it can be useful to be able to use that not only on Android.
- Adds support for loading KTX-texture with mip maps.
- Loosens the PixelFormat functions to be able to work on at least a full slice when pixel format is compressed. Otherwise Metal renderer fails to load pvrtc compressed textures.

Fixes metal pvrtc support

---

RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp

reverts a323cba94073c1f8194bbefdac93ed14c6736240
the "fix" was triggered on unrelated gl errors as glGetError would catch
any error that happened before the lock call.
Furtheremore Mavericks is long gone and we have no reprodcer for this.

GL: drop OSX Mavericks HBL_DISCARD workaround

---

CMake/CMakeLists.txt

Fixed a problem where `FindFreetype.cmake` could not be found during installation.

CMake: fix static build problem

---

OgreMain/include/OgreRenderQueue.h
OgreMain/src/OgreRenderQueue.cpp
OgreMain/src/OgreSceneManager.cpp

RenderQueue: store RenderQueueGroups as plain array instead of std::map

---

OgreMain/src/OgreInstancedEntity.cpp

This fixes a bug where entities that were scaled would get incorrectly
culled from the scene. Since getMaxScaleCoef() is called more
frequently the mMaxScaleLocal is used as cache when there's a parent
scene node.
To see the bug, on could create a scene with a single instanced entity. Change the scale of the entity by some magnitude and move the camera around. As soon as the unscaled version of the instanced entity would be outside of the frustrum the entity will be hidden.

Take scale into account when culling objects.

---

Components/Overlay/src/OgreOverlayManager.cpp

Make overlay definition and opening (with '{') on the same line work.
Resolves #696.

Add warning for improper overlay declaration

---

RenderSystems/GLSupport/src/GLSL/OgreGLSLProgramCommon.cpp

This brings two fixes for `extractLayoutQualifiers()`.
When using both layout location and interpolation qualifiers, I use to write it this way:
```
flat layout(location = 1) out vec4 outColor;
```
However I discovered that this syntax is not supported by the MacOs GLSL compiler. It is hard to find an official documentation to know what is the correct syntax (nothing [here](https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL)) for instance), but I found that this way works on all the platforms I tested so far (Linux, Windows, MacOs):
```
layout(location = 1) flat out vec4 outColor;
```
However, `GLSLProgramCommon::extractLayoutQualifiers(void)` fails to parse this correctly. I propose so to detect the case when a interpolation qualifiers is used and skip it appropriately since it …

GLSupport: fix layout qualifier parsing

---

CMake/Dependencies.cmake
Components/Overlay/CMakeLists.txt

- Building libpng from patched sources.
- Linking to Overlay

CMake: Fix Windows Overlay PNG linking issue.

---

RenderSystems/GLSupport/src/win32/OgreWin32Window.cpp

... which called Win32Window::create in the file
RenderSystems/GLSupport/src/win32/OgreWin32Window.cpp
The crash was at the line:
// Pass pointer to self as WM_CREATE parameter
mHWnd = CreateWindowEx(dwStyleEx, "OgreGLWindow", title.c_str(),
getWindowStyle(fullScreen), mLeft, mTop, mWidth, mHeight, parent, 0, hInst, this);
Introduced in commit aa90530a586d1c484abdf8be316838afe27c7bd1.
Fixes #814.

fix crash in Ogre::Root::getSingleton().createRenderWindow

---

Samples/PNTrianglesTessellation/include/PNTrianglesTessellation.h

Light was being parented to 2 scene nodes, causing OGRE to throw Exception::ERR_INVALIDPARAMS every time the sample was starting.

Samples/PNTriangles: fixed exception in light setup

---

RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp

see https://stackoverflow.com/questions/1108589/is-0-a-valid-opengl-texture-id

GL*: do not needlessly bind zero texture

---

OgreMain/src/OgrePixelFormat.cpp
Samples/Media/DeferredShadingMedia/ssao.compositor
Samples/Media/materials/scripts/Examples.compositor
Samples/Media/materials/scripts/SSAO/SSAO.compositor
Samples/Media/materials/scripts/SSAO/SSAOPost.compositor

and port compositors - instead of hardcoding (A)BGR which on most
platforms requires colour conversions.

Main: allow using native endian byte pixel formats in scripts

---

OgreMain/src/OgreCompositorInstance.cpp

When resizing the render window we sometimes ended up with compositor render targets having a height or a width of 0 resulting in segfault when trying to access the render target's texture buffer.
This is due to the render target's size factor which, when multiplied to the window size, could give a width or height < 1.
I'm not sure if this is the best solution but it may be useful.

Main: prevent compositor instances from having empty render targets

---

OgreMain/include/OgreVector.h

fixes MSVC15 linking of Vector3i

Main: VectorBase - do not mark as export as it is fully inline

---

Components/Bites/include/OgreWindowEventUtilities.h
Components/Bites/src/OgreWindowEventUtilities.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderWindow.cpp
RenderSystems/Direct3D9/src/OgreD3D9RenderWindow.cpp
RenderSystems/GLSupport/src/win32/OgreWin32Window.cpp

Now users upgrading from 1.10 to 1.11 can keep using Ogre window system by providing the `_WndProc` in the `miscParams`:
```c++
Ogre::NameValuePairList miscParams;
miscParams["windowProc"] = Ogre::StringConverter::toString((size_t)OgreBites::WindowEventUtilities::_WndProc);
Ogre::RenderWindow* renderWindow = Ogre::Root::getSingleton().createRenderWindow(name, width, height, isFullScreen, &miscParams);
OgreBites::WindowEventUtilities::_addRenderWindow(renderWindow);
```

Reintroduce _WndProc from 1.10

---

Components/RTShaderSystem/src/OgreShaderProgramManager.cpp

RTSS: skip binding samplers on HLSL

---

Components/Bites/src/OgreApplicationContext.cpp
RenderSystems/GLSupport/src/GLX/OgreGLXWindow.cpp

and consequently remove superficial resize call in Bites

GLSupport: GLX - correctly handle windowMovedOrResized with parent win

---

Docs/CMakeLists.txt
Docs/src/manual.md
Docs/src/resourcemanagement.md
OgreMain/include/OgreResource.h
OgreMain/include/OgreResourceGroupManager.h
OgreMain/include/OgreResourceManager.h

instead of spreading it across multiple API calls

Docs: Resource Management - group information on a single manual page

---

RenderSystems/GLSupport/include/EGL/OgreEGLSupport.h
RenderSystems/GLSupport/src/EGL/OgreEGLSupport.cpp

This fix on two of the functions return config id as EGL config which eventually cause EGL error when create the EGL context by such "config".

Fixed incorrect EGL config id return as EGL config

---

Components/Bites/src/OgreApplicationContext.cpp

Return created render window and native window pair instead of pair of null values in Android platform of the ApplicationContext::createWindow function.

Correct return value for ApplicationContext::createWindow in Android

---

OgreMain/src/Android/OgreAPKFileSystemArchive.cpp

This fixed the crash issue in Android when ApplicationContext::closeApp() called

erase the element that should be existed in the map

---

RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp

D3D11: also use _getTextureBindFlags for 3D textures

---

RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp

d3dx did some magic while loading. probably storing it uncompressed.

D3D9: drop actually unsupported RSC_AUTOMIPMAP_COMPRESSED

---

RenderSystems/Direct3D9/src/OgreD3D9Texture.cpp

D3D9: do not crash when moving window to the second screen

---

RenderSystems/Direct3D9/src/OgreD3D9Texture.cpp

as the other paths still should work fine

D3D9: only disable texture loading from getBuffer

---

OgreMain/src/OgreRenderSystem.cpp
RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp

fixes exception on blank texture in D3D9

Main: unify handling of blank textures

---

Components/Bites/CMakeLists.txt
Components/Bites/include/OgreApplicationContext.h
Components/Bites/include/OgreApplicationContextBase.h
Components/Bites/include/OgreBites.i
Components/Bites/src/OgreApplicationContextAndroid.cpp
Components/Bites/src/OgreApplicationContextBase.cpp
Components/Bites/src/OgreApplicationContextSDL.cpp

and move SDL2 and Android code into deriving classes

Bites: extract ApplicationContextBase to allow multiple implementations

---

Components/Bites/src/OgreTrays.cpp
Components/Overlay/include/OgreOverlayElement.h
Components/Overlay/include/OgreUTFString.h
Components/Overlay/src/OgreTextAreaOverlayElement.cpp
Components/Overlay/src/OgreUTFString.cpp
OgreMain/include/OgreDynLib.h
OgreMain/include/OgrePlatform.h
OgreMain/src/OgreDynLib.cpp

also get rid of no longer needed OGRE_UNICODE_SUPPORT: since it was set to 0 only for the gcc3 on mingw, which is no longer supported (no C++11)

move OgreUTFString to Overlay component

---

Components/Bites/src/OgreApplicationContextBase.cpp

as the first window owns the GL context

Bites: ApplicationContext - windows must be destroyed in reverse order

---

Tests/VisualTests/PlayPen/src/PlayPenTests.cpp

that somehow corrupted the vertex arrays in later tests on GL3+/ GLES2

VTests: drop superficial calls to buildTangentVectors on knot.mesh

---

RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp

This initializes a HRESULT value that may not be initialized.
If this value is not changed, it may fail on this [lines](https://github.com/OGRECave/ogre/blob/25f5808a8e27c6ae511ebec1c98b104e22840fd7/RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp#L256-L257).

D3D9: Small fix for FFP params

---

Components/Overlay/src/OgreBorderPanelOverlayElement.cpp
Components/Overlay/src/OgrePanelOverlayElement.cpp
Components/Overlay/src/OgreTextAreaOverlayElement.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusHardwareBuffer.cpp

Changed Overlay components buffers to use shadowbuffer. This will avoid the buffer mapping path in rendersystems, which caused stalls in multithread enabled drivers.

Overlay buffer mapping workaround

---

OgreMain/src/OgreResourceGroupManager.cpp
Tests/OgreMain/include/ResourceLocationPriorityTest.h
Tests/OgreMain/src/ResourceLocationPriorityTest.cpp

[The documentation](https://ogrecave.github.io/ogre/api/latest/_resource-_management.html#Resource-Location) states that resource locations added first are preferred over those added later. Currently this is not the case because `ResourceGroup::addToIndex` overwrites the stored `Archive` for any file that has already been found; if two files with the same name exist in different resource locations, then the file in the location added *last* will take priority. 
This fixes the ordering and adds a test to check the correct behaviour. A `DummyArchive` class is used to save modifying `resources.cfg` by adding another resource location.
I've tried to follow the existing coding conventions as closely as possible, but if anything's wrong I'll gladly make changes.

Fix resource location priority

---

BuildingOgre.md

and move Windows Phone instructions to bottom

Docs: update building instructions for android

---

OgreMain/include/OgreSharedPtr.h

This allows code like
```cpp
Ogre::MeshPtr maybeGetMyMesh() {
// Do stuff
if (someFailure) return nullptr;
// Do stuff
}
```
which would otherwise work with `std::shared_ptr`.

Add missing nullptr_t constructor for SharedPtr

---

Components/Overlay/src/OgreTextAreaOverlayElement.cpp

This fixes a bug where calling `TextAreaOverlayElement::setFontName` wouldn't change the font if it had already been set before. This is because `mMaterial` wasn't being updated in `getMaterial` if it had been set previously, and so it would still point to the old font's material (and textures).

Overlay: fix TextArea Font and material change

---

RenderSystems/Direct3D11/include/OgreD3D11MultiRenderTarget.h
RenderSystems/Direct3D11/include/OgreD3D11Prerequisites.h
RenderSystems/Direct3D11/include/OgreD3D11RenderTarget.h
RenderSystems/Direct3D11/include/OgreD3D11RenderWindow.h
RenderSystems/Direct3D11/include/OgreD3D11Texture.h
RenderSystems/Direct3D11/src/OgreD3D11DepthBuffer.cpp
RenderSystems/Direct3D11/src/OgreD3D11MultiRenderTarget.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderWindow.cpp
RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp

I created the `D3D11RenderTarget` class/interface and inherited some classes from it.
However, I dont know if this is the best way.
Also, the related calls to the `getCustomAttribute()` methods have not been replaced yet.
Related to #1191.

D3D11: Replaced the use of getCustomAttribute() methods by new D3D11RenderTarget interface

---

Tools/XMLConverter/src/OgreXMLMeshSerializer.cpp
Tools/XMLConverter/src/main.cpp

it is invalid and triggers an assertion, but lets be tolerant to old XML
files.

XMLConverter: do not attempt to create "" named materials

---

OgreMain/src/OgreException.cpp

- it calls a virtual function which is UB
- Ogre uses exceptions for internal communication which must be fast
- the messages were only ever received by log-listeners

Main: remove logging from Exception constructor altogether

---

RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm

The `currentGLContext` parameter is defined in the [`Ogre::Root::createRenderWindow()` documentation](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_root.html#a537b7d1d0937f799cfe4936f6b672620) but was not implemented for macOS (it works fine on Windows and Linux).
I think it would be more convenient to have this option on all platforms so here's the implementation.
I hope you'll find it useful.
Cheers.

GLSupport: implement the 'currentGLContext' parameter for macOS cocoa windows 

---

RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLMonolithicProgram.cpp

I was having a problem when a monolithic GLSL program was re-linked.
The program was re-created through `glCreateProgram` leaking the old one.
I found this error when trying to set transform feedback varyings with [this function](https://www.lgdv.tf.fau.de/publicationen/adaptive-temporal-sampling-for-volumetric-path-tracing-of-medical-data/). `glTransformFeedbackVaryings` was called on the old programId and had therefore no effect.

GL3+: fix leak when a program object is created but one already exists

---

Components/Overlay/include/OgreUTFString.h
Components/Overlay/src/OgreUTFString.cpp
OgreMain/include/OgreMath.h
OgreMain/include/OgrePolygon.h
OgreMain/include/OgreQuaternion.h
OgreMain/include/OgreSharedPtr.h
OgreMain/src/OgrePolygon.cpp
OgreMain/src/OgreVertexIndexData.cpp

This doesn't change anything, but it appeases gcc 9.2.1 which otherwise
absolutely spams the console with warnings about mixing implicit and
explicit copy constructors.
This implementation should work with C++98.

Provide copy and assign ctors where needed.

---

Docs/CMakeLists.txt

This fits with the Filesystem Hierarchy Standard. It also helps with
packaging of OGRE, since some systems require that all directories
is owned by one single package. Thus it's beneficial if the docs are
kept separate from the media.

Install Linux docs in /usr/share/doc/OGRE

---

OgreMain/include/OgreMath.h
OgreMain/include/OgreRenderSystem.h
OgreMain/src/OgreFrustum.cpp
OgreMain/src/OgreMath.cpp
OgreMain/src/OgreRenderSystem.cpp
RenderSystems/GL3Plus/include/OgreGL3PlusRenderSystem.h
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLSupport/include/OgreGLRenderSystemCommon.h
RenderSystems/GLSupport/src/GLSL/OgreGLSLShaderCommon.cpp
RenderSystems/GLSupport/src/OgreGLRenderSystemCommon.cpp

RenderSystem has new function setReverseDepthBuffer for controlling if this is enabled. This function must be called early to take effect.
glClipControl was not found in old gl3w so it had to be updated as well.
GLSL shaders will have REVERSE_Z_BUFFER define defined when reverse depth buffer is in use.
* Implementations that used gl_Position.z for calculating fog for example need to change their implementation and this define can be used for that.
Normally OpenGL has it's depth range from -1 to 1 but this flag will change it to be from 1 to 0.

Reverse depth buffer implementation for OpenGL3+

---

OgreMain/include/OgreMath.h
OgreMain/src/OgreFrustum.cpp
OgreMain/src/OgreMath.cpp
RenderSystems/GLSupport/src/OgreGLRenderSystemCommon.cpp

The problem was when using custom near clip plane. I have undone the frustum changes and made correct projection matrix change in the `GLRenderSystemCommon::_convertProjectionMatrix` function. This makes even the custom near clip plane work correctly with the reversed z buffer.

Reverse Z-buffer introduced invalid projection matrix

---

OgreMain/include/OgreRenderSystem.h
OgreMain/src/OgreRenderSystem.cpp
RenderSystems/GL3Plus/include/OgreGL3PlusRenderSystem.h
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp

this ensures it is enabled early on and that it cannot be enabled on
RenderSystems not explicitly supporting it.

Main: make reverse-Z a ConfigOption and check compatibility in GL3Plus

---

Samples/CMakeLists.txt

Otherwise cmake errors with `Cannnot find target SampleBrowser`

🐛 Do not build demo installer when SampleBrowser is disabled

---

OgreMain/CMakeLists.txt

Otherwise Visual Studio will complain "precompiled header file is from a previous version of the compiler, or the precompiled header is C++ and you are using it from C (or vice versa)".

Compile Remotery.c as cpp-file

---

RenderSystems/GLSupport/include/OSX/OgreOSXCocoaWindow.h
RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm

The option was missing for macOS but described in the [`Ogre::Root::createRenderWindow`](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_root.html#a537b7d1d0937f799cfe4936f6b672620) documentation.

GLSupport: add the 'externalGLControl' option to Cocoa render windows

---

RenderSystems/Direct3D11/src/OgreD3D11Device.cpp

The Microsoft documentation recommends that Flush should be called after ClearState.
https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-flush

Switched ClearState and Flush

---

Tools/XMLConverter/src/OgreXMLSkeletonSerializer.cpp
Tools/XMLConverter/src/main.cpp

XMLConverter: validate bone ids and use logError for colored output

---

Components/Overlay/include/OgreOverlay.i

Replaced the Swig mapping and allows the use of the classes.

Changed Swig SharedPtr to Ogre SharedPtr.

---

OgreMain/include/Ogre.i

It's only the most basic solution from [Swig Overloaded operators](http://www.swig.org/Doc4.0/SWIGDocumentation.html#SWIGPlus_nn28).

Added overloaded addition, subtraction, multiplication and division.

---

Components/RTShaderSystem/include/OgreShaderFFPTransform.h
Components/RTShaderSystem/include/OgreShaderParameter.h
Components/RTShaderSystem/src/OgreShaderFFPTransform.cpp
Components/RTShaderSystem/src/OgreShaderGLSLProgramWriter.cpp
Components/RTShaderSystem/src/OgreShaderParameter.cpp
Docs/src/rtss.md
RenderSystems/Direct3D11/src/OgreD3D11VertexDeclaration.cpp
RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp
Samples/Media/materials/programs/GLSL120/HWBasicInstancing.vert
Samples/Media/materials/programs/GLSLES/HWBasicInstancing.vert
Samples/Media/materials/programs/HLSL_Cg/HWBasicInstancing.cg
Samples/Media/materials/scripts/HWInstancing.material

- custom instancing shaders are broken (fix them first?)
fixes #1024

RTSS - add hardware instancing support

---

OgreMain/include/Ogre.i

The changes are for the C# wrapper.
They allow the use of System.IntPtr instead of void* marshalling of Swig and it is possible to create Vertex Buffers with Code like that:
```
var vertexBuffer = HardwareBufferManager.getSingleton().createVertexBuffer(offset, vertexCount, HardwareBuffer.Usage.HBU_STATIC_WRITE_ONLY);
vertexBuffer.writeData(0, vertexBuffer.getSizeInBytes(), new IntPtr(verticesPtr), true);
```
The second change makes the implementation of this tutorial possible, there I needed to cast MovableObject to Entity
http://wiki.ogre3d.org/Raycasting+to+the+polygon+level

Void Pointer and casting of MovableObject

---

OgreMain/src/OgreResourceManager.cpp

The iterator of a map returned by the find() method was used without checking it for validity.
This caused a crash.

Fixed possible crash in the addImpl() method of the ResourceManager class

---

Components/Overlay/include/OgreOverlay.i

SWIG: allow building Overlay bindings without imgui

---

CMake/Utils/PrecompiledHeader.cmake

Add "-c" argument when building precompiled headers to fix build with
RELRO.
More information on a similar issue with domoticz can be found here:
https://patchwork.ozlabs.org/patch/1187328:
"The problem AFAICS is that if no -c or similar option is given, GCC
decides what needs to be done based on the rest of the arguments. If the
rest of the arguments include a -Wl,... option, it decides that linking
needs to be done. If the rest of the arguments are just header files, it
decides to create a precompiled header."
Fixes:
- http://autobuild.buildroot.org/results/8fabf8d270b9257c3a9db6a2f17f1c08ec9428d3
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

CMake/Utils/PrecompiledHeader.cmake: Add -c argument to build precompiled headers

---

CMake/ConfigureBuild.cmake
CMake/Templates/OgreBuildSettings.h.in
OgreMain/include/OgreString.h

strtol_l, strtoul_l, strtoll_l and strtoull_l are not always available
(for example on musl) so check for them and define a fallback if needed
to avoid the following build failure:
```
/home/buildroot/autobuild/instance-1/output-1/build/ogre-1.12.0/OgreMain/src/OgreStringConverter.cpp: In static member function 'static bool Ogre::StringConverter::parse(const String&, Ogre::int32&)':
/home/buildroot/autobuild/instance-1/output-1/build/ogre-1.12.0/OgreMain/src/OgreStringConverter.cpp:253:22: error: 'strtol_l' was not declared in this scope
ret = (int32)strtol_l(val.c_str(), &end, 0, _numLocale);
^~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/107cffe41081ce46441dec8699d6ad0f152bc152
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Checks for strtol_l functions

---

RenderSystems/GL/include/OgreGLRenderSystem.h
RenderSystems/GL/src/GLSL/include/OgreGLSLProgram.h
RenderSystems/GL/src/GLSL/src/OgreGLSLProgram.cpp
RenderSystems/GL/src/OgreGLRenderSystem.cpp
Tests/VisualTests/Context/src/TestContext.cpp

useful for porting to GL3+ or to improve performance if only shaders are
used
fixes #1467

GL: add ConfigOption to disable FFP

---

OgreMain/include/OgreAnimable.h
OgreMain/include/OgreAnimationState.h
OgreMain/include/OgreGpuProgramParams.h
OgreMain/include/OgreInstanceManager.h
OgreMain/include/OgreRenderSystemCapabilities.h
OgreMain/include/OgreRenderable.h
OgreMain/include/OgreStringInterface.h
OgreMain/include/OgreTextureManager.h
OgreMain/include/OgreTextureUnitState.h
OgreMain/include/OgreUserObjectBindings.h
OgreMain/src/OgreAnimable.cpp
OgreMain/src/OgreAnimationState.cpp
OgreMain/src/OgreGpuProgramParams.cpp
OgreMain/src/OgreInstanceManager.cpp
OgreMain/src/OgreRenderSystemCapabilities.cpp
OgreMain/src/OgreRenderable.cpp
OgreMain/src/OgreStringInterface.cpp
OgreMain/src/OgreTextureManager.cpp
OgreMain/src/OgreTextureUnitState.cpp
OgreMain/src/OgreUserObjectBindings.cpp

notably StringInterface and map related methods.
Compilation (524 times):
Parsing (frontend):          931.2 s
Codegen & opts (backend):    474.7 s
Compilation (525 times):
Parsing (frontend):          786.6 s
Codegen & opts (backend):    450.5 s
no significant compile time reduction on CI.

Main: deinline non performance-critical methods to improve compile speed

---

BuildingOgre.md

`Ogre `is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for ogre and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build ogre, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/ogre/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

Add vcpkg installation instructions

---

OgreMain/include/Ogre.i

The non member operator overloads were not wrapped by Swig.
In order to to that the %extend directive must be used in the Swig interface file.

Main: Swig - extend Matrix3, Matrix4 and Affine3 by non member operator overloads

---

Components/RTShaderSystem/src/OgreShaderGLSLESProgramWriter.cpp

```cpp
functionInvoc = createInvocationFromString(functionSig);
// Ok, now if we have found the signature, iterate through the file until we find the end
// of the function.
bool foundEndOfBody = false;
size_t braceCount = 0;
while(!foundEndOfBody)
{
functionBody += line;
String::size_type brace_pos = line.find('{', 0);
if(brace_pos != String::npos)
{
braceCount++;
}
brace_pos = line.find('}', 0);
if(brace_pos != String::npos)
braceCount--;
if(braceCount == 0)
{
foundEndOfBody = true;
// Remove first and last braces
size_t pos = functionBody.find('{');
functionBody.erase(pos, 1);
pos = functionBody.rfind('}');
functionBody.erase(pos, 1);
mFunctionCacheMap.emplace(*functionInvoc, functionBody);
}
functionBody += "\n";
line = stream->getLine();
}
```
The **emplace** method is value copy, so …

Main: RenderSystem - fix FunctionInvocation leak

---

.travis.yml
CMake/Dependencies.cmake
CMake/FeatureSummary.cmake
Components/Bites/CMakeLists.txt
Components/Bites/include/OgreApplicationContextQt.h
Components/Bites/src/OgreApplicationContextQt.cpp

Qt implementation of ApplicationContext

---

OgreMain/include/OgreGpuProgramParams.h
OgreMain/src/OgreGpuProgramParams.cpp

Related to issue https://github.com/OGRECave/ogre/issues/1476
Matrices params size was not properly handled when calculating the aligned offset.
This new fix should handle every case.
Tested it against this Uniform block:
```
layout(std140) uniform TestAlignment
{
mat3 _mat33 ; 	//0
mat4x3 _mat43 ; //48
float _float ; 	//112
mat3x4 _mat34 ; //128
vec3 _vec3;	//176
vec2 _vec2; 	//192
mat4 _mat44; 	//208
float _float1; 	//272
float _float2; 	//276
mat3 _mat33_2; 	//288
mat2 _mat22 ;	//336
};
```

Fixed badly calculated matrices alignement

---

OgreMain/CMakeLists.txt

We failed to build ogre in https://github.com/conda-forge/ogre-feedstock/pull/24 after https://github.com/OGRECave/ogre/commit/397e24cfc4ec96f35cab41c99a05d0458af7e1a0 was merged (see https://github.com/conda-forge/ogre-feedstock/pull/24).
This patch fixes the build (see https://github.com/conda-forge/ogre-feedstock/pull/25). It would be great if it could be merged.
Many thanks,
Tobias

Fix OSX platform libs

---

OgreMain/include/OgreCamera.h
OgreMain/include/OgreCompositionTechnique.h
OgreMain/include/OgreGpuProgram.h
OgreMain/include/OgreMaterial.h
OgreMain/include/OgreRenderSystem.h
OgreMain/include/OgreSceneManagerEnumerator.h
OgreMain/include/OgreScriptCompiler.h
OgreMain/include/OgreTechnique.h
OgreMain/include/OgreTexture.h
OgreMain/include/OgreTextureUnitState.h
OgreMain/src/OgreCamera.cpp
OgreMain/src/OgreMaterial.cpp
OgreMain/src/OgreMeshSerializerImpl.cpp
OgreMain/src/OgrePass.cpp
OgreMain/src/OgreRenderQueue.cpp
OgreMain/src/OgreRenderSystem.cpp
OgreMain/src/OgreRoot.cpp
OgreMain/src/OgreScriptTranslator.cpp
OgreMain/src/OgreStableHeaders.h
OgreMain/src/OgreSubMesh.cpp
OgreMain/src/OgreTextureManager.cpp
OgreMain/src/OgreTextureUnitState.cpp
PlugIns/CgProgramManager/src/OgreCgProgram.cpp
RenderSystems/Direct3D11/include/OgreD3D11RenderSystem.h
RenderSystems/Direct3D11/include/OgreD3D11TextureManager.h
RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
RenderSystems/Direct3D11/src/OgreD3D11TextureManager.cpp

also likely fixes some bugs as sampler settings were all over the place

D3D11: port to Sampler object. Enables caching of ID3D11SamplerState

---

Components/Overlay/include/OgreOverlaySystem.h
Components/Overlay/src/OgreOverlaySystem.cpp

rationale: it internally manages singletons and functionality was previously in Root, which is also a singleton.
fixes #112

Overlay: make OverlaySystem a Singleton

---

OgreMain/include/OgreSceneManager.h
OgreMain/src/OgreSceneManager.cpp
OgreMain/src/OgreSkyRenderer.cpp
PlugIns/PCZSceneManager/src/OgrePCZSceneManager.cpp

dropped remaining Sky special casing, except in PCZSceneManager

Main: split SkyRenderer into Plane, Box and Dome classes

---

OgreMain/src/OgreScriptTranslator.cpp

fixes fallout of e1b7ccc77f4e1ccf5ffe9724d3caafd9262a6fe3

Main: ScriptTranslator - revert to legacy "alpha" keyword translation

---

OgreMain/src/OgrePlatformInformation.cpp

This file includes `<sys/sysctl.h>` if the CPU is ARM, which breaks compilation with the upcoming glibc 2.32 release because that header has been removed. The header only seems to be needed for `sysctlbyname`, which is only used on iOS. Change the `#ifdef` to avoid including it when not needed.
This fixes a build failure in Fedora rawhide: https://bugzilla.redhat.com/show_bug.cgi?id=1841324

Only include <sys/sysctl.h> for iOS

---

Docs/src/high-level-programs.md
Media/ShadowVolume/HLSL_SM4Support.hlsl
OgreMain/src/OgreHighLevelGpuProgram.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
RenderSystems/Direct3D9/include/OgreD3D9RenderSystem.h
RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp

to get rid of namespace polluting SHADER_MODEL_4 define

Main: pass native shader version to shaders as e.g. OGRE_HLSL=4

---

PlugIns/Assimp/src/AssimpLoader.cpp

also registered by FreeImage for "Mintola Digital Camera". FreeImage was
first.

Plugins: Assimp - blacklist mdc file format

---

Components/Bites/src/OgreApplicationContextBase.cpp
Docs/src/tutorials/setup.md

To allow loading config files (e.g. plugins.cfg, resources.cfg) from
arbitrary locations. Up to now it was only possible to load them from
- the CWD,
- the writable path (i.e. somewhere in HOME),
- the location Ogre was originally installed to.
Also resolve relative paths in `resources.cfg` relative to the config-file location.
This commit is especially useful, if you need to start your
application from anywhere else than the location of the config-files.

Improve config-path resolution

---

RenderSystems/GLSupport/src/EGL/Emscripten/OgreEmscriptenEGLWindow.cpp
Samples/Emscripten/CMakeLists.txt

fixes #1697 
fixes #1686
fixes #1289
These changes enable the use the latest versions of emscripten. Latest version of emscripten has several fixes including handling of fullscreen see [changelog](https://github.com/emscripten-core/emscripten/blob/master/ChangeLog.md) not to mention it now uses LLVM backend.[ emscripten-llvm-wasm](https://v8.dev/blog/emscripten-llvm-wasm) which has several benefits.

Fixes issue preventing use of latest emscripten versions

---

OgreMain/include/OgrePlatform.h
OgreMain/include/OgrePlatformInformation.h

aka Apple Silicon; moved to Platform.h as it is already used there.

Main: cleaned definition to fix build for macOS on ARM64

---

Components/Overlay/include/OgreOverlay.i

getting still broken
fixes #1663

SWIG: Overlay - add workaround for setting DisplayString parameters

---

OgreMain/src/OgreGpuProgramParams.cpp

There was a typo wich would lead to misleading OGRE Exception text.

Fix Typo in GpuNamedConstantsSerializer::exportNamedConstants

---

.travis.yml
CMakeLists.txt
Components/Terrain/src/OgreTerrain.cpp
OgreMain/include/OgreImage.h
OgreMain/src/OgreImage.cpp
OgreMain/src/OgreRenderTarget.cpp
OgreMain/src/OgreTexture.cpp
OgreMain/src/OgreTextureManager.cpp

-  allow allocating empty memory upon construction as a safe malloc replacement
- expose loadDynamicImage as a constructor
- implement setting whole Image to a specific colour

Main: make Image class more versatile

---

OgreMain/include/OgreMovableObject.h

Overriding of destroyInstance of class MovableObjectFactory is used in OgreOggSound. And what is point to keep it non-virtual when user must define creation logic in createInstanceImpl anyway?

destroyInstance method shoud be marked virtual

---

Components/Overlay/include/OgreOverlay.i

I needed to cast from OverlayElement to OverlayContainer to recreate this tutorial: http://wiki.ogre3d.org/Creating+Overlays+via+Code

Added cast from OverlayElement to OverlayContainer

---

Components/Overlay/src/OgreImGuiOverlay.cpp

Overlay: ImGuiOverlay - avoid recreating buffers at every draw call

---

Components/RTShaderSystem/src/OgreShaderFFPTexturing.cpp
OgreMain/src/OgrePass.cpp

otherwise it would still attempt to use texcoords

handle missing RSC_POINT_SPRITES support in RTSS

---

RenderSystems/GLSupport/include/win32/OgreWin32Context.h
RenderSystems/GLSupport/include/win32/OgreWin32GLSupport.h
RenderSystems/GLSupport/include/win32/OgreWin32RenderTexture.h
RenderSystems/GLSupport/src/win32/OgreWin32Context.cpp
RenderSystems/GLSupport/src/win32/OgreWin32GLSupport.cpp
RenderSystems/GLSupport/src/win32/OgreWin32RenderTexture.cpp
RenderSystems/GLSupport/src/win32/OgreWin32Window.cpp

for context ceation. Similar to GLX. Allows using renderdoc.

GLSupport: Win32 - use CreateContextAttribs

---

Components/Terrain/include/OgreTerrainQuadTreeNode.h
Components/Terrain/src/OgreTerrain.cpp
Components/Terrain/src/OgreTerrainAutoUpdateLod.cpp
Components/Terrain/src/OgreTerrainQuadTreeNode.cpp
OgreMain/include/OgreMovableObject.h

to fix TerrainQuadTreeNode which stores this in its parent

Main: MovableObject - make getVisibilityFlags getQueryFlags virtual

---

CMake/Utils/PrecompiledHeader.cmake
Components/RTShaderSystem/include/OgreShaderFunction.h
Components/RTShaderSystem/src/OgreShaderFunction.cpp
OgreMain/include/OgreString.h
OgreMain/src/OgreDataStream.cpp
OgreMain/src/OgreHighLevelGpuProgram.cpp
OgreMain/src/OgreStaticGeometry.cpp
RenderSystems/GL/src/OgreGLRenderToVertexBuffer.cpp
RenderSystems/GL/src/nvparse/_vs1.0_lexer.cpp
RenderSystems/GL/src/nvparse/vs1.0_tokens.l
RenderSystems/GL3Plus/src/OgreGL3PlusRenderToVertexBuffer.cpp
RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESCgProgram.cpp
RenderSystems/GLES2/src/OgreGLES2RenderToVertexBuffer.cpp
Tools/XSIExport/OGREXSI_Readme.html
Tools/XSIExport/include/OgreXSIMeshExporter.h

https://games-team.pages.debian.net/-/ogre/-/jobs/1292553/artifacts/debian/output/lintian.html
complains about a few typos in strings. I couldn't find all of them but also found a few additional occurrences in variable names etc.

fix spelling errors reported by lintian

---

Components/RTShaderSystem/src/OgreShaderGenerator.cpp
Tests/Components/RTShaderSystemTests.cpp

this is a common issue when addSceneManager is omitted by accident

RTSS: assert that we have a sceneManager in synchronizeWithLightSettings

---

OgreMain/src/OgreRenderSystem.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp

also allows using CSAA on AMD with D3D9 and fixes parsing of CSAA level
fixes #1419

D3D*: fix braindead CSAA naming and mode selection

---

PlugIns/DotScene/README.md

I had a lot of trouble understanding how to use the Plugin, most of the information is in this thread: https://forums.ogre3d.org/viewtopic.php?t=96069 but it is not clear how to do it the modern way.
Eventually found the code in OgreSceneLoader.cpp, but new users should have an easier time using this important plugin.
If this gets accepted, I will see if the manual can be modified to put an example.

Add DotScene usage scenarios

---

OgreMain/include/OgreFrustum.h

The description of getNearClipDistance() was incorrect.

Fix description of getNearClipDistance()

---

PlugIns/DotScene/src/DotSceneLoader.cpp

The inner and outer angles of the SpotLight are being interpreted as Degrees, but the blender2ogre exporter is exporting the value in Radians.
For some reason in that context Angle is interpreting the input as Degrees.
I also changed parseQuaternion() for consistency although it seems to be working alright there.

Correct angle parsing

---

OgreMain/include/OgreLight.h

Correct wrong wording in `getPowerScale()` and while we are at it change all the 'Gets' to 'Returns' for consistency.

Correct some erroneous wording and apply consistency.

---

OgreMain/include/OgreBitwise.h

bswapX macros are defined on other BSD systems too, so it's easier to just undefine them if they're already defined.
this fixes the build on NetBSD.

build fix: remove unnecessary #ifdef __FreeBSD__

---

Components/Overlay/include/OgreOverlay.h
Components/Overlay/include/OgreOverlayElement.h
Components/Overlay/src/OgreOverlay.cpp
Components/Overlay/src/OgreOverlayElement.cpp

Just added `setVisible` because with `show` and `hide` I have to evaluate what function to call in my code which results in a branch.
I do not like that now `show`, `hide` and `setVisible` are all virtual in `OgreOverlayElement`.
There are better alternatives to allow the inherited classes special behavour on visibility changes in this case.
But I do not want to introduce a breaking API change.

Overlay: add setVisible to OgreOverlay and OgreOverlayElement

---

Tools/MeshUpgrader/src/main.cpp

It is possible to generate a `.mesh` without an assigned material so the name will be blank.
In this case the following assert is triggered:
```
File: D:\OGRE2\Sources\ogre-master\OgreMain\src\OgreResourceManager.cpp, Line 50
Expression: (!name.empty()) && ("resource name must not be empty")
```

When the mesh has no material assigned an assertion is triggered

---

CMake/Utils/PrecompiledHeader.cmake

Using GREATER_EQUAL breaks build file generation for CMake versions less than 3.7. Use "NOT ... VERSION_LESS" instead.

Fix PrecompiledHeader.cmake for old CMake versions

---

Docs/src/manual.md

This section is being references from OgreXMLConverter when an empty material name is being set, which is something that could backfire for the user eventually.

Add section about empty Material Names

---

Tools/MeshUpgrader/src/main.cpp

- Inconsistent mixture of cout and std::cout
- Make the exceptions stand out from the rest of the output

Fix some formatting regarding console output

---

BuildingOgre.md

Docs: BuildingOgre - fix target names for OSX which is case-sensitive

---

PlugIns/DotScene/include/OgreDotSceneLoader.h
PlugIns/DotScene/misc/dotscene.dtd
PlugIns/DotScene/src/DotSceneLoader.cpp

Add support for node animation, the idea originates from [NodeAnimation exporter #58](https://github.com/OGRECave/blender2ogre/issues/58)
- The code is based on the EasyOgreExporter that has already implemented it
- Modified the DTD to reflect the node animations
- Added functions to DotSceneLoader to process the animation data
- Added logging to most functions in DotSceneLoader

DotSceneLoader - Node animation support

---

Components/RTShaderSystem/src/OgreShaderProgramManager.cpp
Components/Terrain/src/OgreTerrainMaterialShaderHelperGLSL.cpp
OgreMain/include/OgrePrerequisites.h
OgreMain/include/OgreScriptCompiler.h
OgreMain/include/OgreUnifiedHighLevelGpuProgram.h
OgreMain/src/OgreHighLevelGpuProgramManager.cpp
OgreMain/src/OgreScriptCompiler.cpp
OgreMain/src/OgreScriptTranslator.cpp
OgreMain/src/OgreUnifiedHighLevelGpuProgram.cpp

and derive UnifiedHighLevelGpuProgram and NullProgram from GpuProgramPtr
fixes #1368 
we cannot unify any further as:
- HighLevelProgramManager has its own resource namespace right now, merging with low level would cause conflicts in user code
- The factory classes do not consider syntax, which requires special hacks

Main: make HighLevelGpuProgramPtr an alias for GpuProgramPtr

---

Components/RTShaderSystem/src/OgreShaderProgramProcessor.cpp
OgreMain/include/Ogre.i
OgreMain/include/OgreGpuProgram.h
OgreMain/include/OgreGpuProgramParams.h
OgreMain/include/OgreHighLevelGpuProgram.h
OgreMain/src/OgreGpuProgram.cpp
OgreMain/src/OgreGpuProgramParams.cpp
OgreMain/src/OgreHighLevelGpuProgram.cpp
OgreMain/src/OgreMaterialSerializer.cpp
OgreMain/src/OgreRenderSystem.cpp
PlugIns/CgProgramManager/src/OgreCgProgram.cpp
RenderSystems/Direct3D11/src/OgreD3D11HLSLProgram.cpp
RenderSystems/Direct3D9/src/OgreD3D9HLSLProgram.cpp
RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp
RenderSystems/GL/src/GLSL/src/OgreGLSLProgram.cpp
RenderSystems/GL/src/OgreGLGpuNvparseProgram.cpp
RenderSystems/GL/src/OgreGLGpuProgram.cpp
RenderSystems/GL/src/atifs/src/ATI_FS_GLGpuProgram.cpp
RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLMonolithicProgram.cpp
RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLSeparableProgram.cpp
RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLShader.cpp
RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESLinkProgram.cpp
RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgram.cpp
RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramPipeline.cpp
RenderSystems/GLSupport/src/GLSL/OgreGLSLProgramManagerCommon.cpp
RenderSystems/Metal/src/OgreMetalProgram.mm
RenderSystems/Metal/src/OgreMetalRenderSystem.mm
RenderSystems/Tiny/src/OgreTinyRenderSystem.cpp

store all constants in a single byte buffer instead of splitting them by
type.
This will allow backing them by HW UBOs and updating with a single
memcpy.

Main: GpuProgramParams - use unified constant storage

---

OgreMain/src/OgreInstanceManager.cpp

This fixes a segfault which will appear if a mesh with shared vertices and existing edge data is used.
It's triggered by the calls to "buildEdgeList()", since when doing this the LODs will be accessed.
And since they haven't been altered, they will rely on the now deleted shared geometry, and
their indices will be out of bounds, causing segfault.

Main InstanceManager - unshare LODs as well

---

OgreMain/src/OgreDefaultDebugDrawer.cpp

Since this will cause an assert error when built in debug mode,
and undefined behaviour if not.

Main: DefaultDebugDrawer -Skip bounding boxes that are infinite.

---

Docs/src/bibliography.bib
OgreMain/include/OgreMath.h
OgreMain/src/OgreMath.cpp
Tests/OgreMain/src/General.cpp

it does not require a normal and is 25% faster for the common case,
where we hit the triangle plane and even 50% faster if we would compute
a normal first.
When shooting the ray away from the triangle, it is >45% slower though.

Main: Math - Use Möller-Trumbore ray-triangle intersection algorithm

---

OgreMain/include/OgreAnimationTrack.h
OgreMain/include/OgreCompositionTargetPass.h
OgreMain/include/OgreCompositionTechnique.h
OgreMain/include/OgreCompositor.h
OgreMain/include/OgreCompositorChain.h
OgreMain/include/OgreCompositorInstance.h
OgreMain/include/OgreEntity.h
OgreMain/include/OgreManualObject.h
OgreMain/include/OgreMaterial.h
OgreMain/include/OgreMesh.h
OgreMain/include/OgrePass.h
OgreMain/include/OgreRenderTexture.h
OgreMain/include/OgreRibbonTrail.h
OgreMain/include/OgreSceneNode.h
OgreMain/include/OgreTechnique.h
OgreMain/src/OgreAnimationTrack.cpp
OgreMain/src/OgreCompositionTargetPass.cpp
OgreMain/src/OgreCompositionTechnique.cpp
OgreMain/src/OgreCompositor.cpp
OgreMain/src/OgreCompositorChain.cpp
OgreMain/src/OgreCompositorInstance.cpp
OgreMain/src/OgreEntity.cpp
OgreMain/src/OgreManualObject.cpp
OgreMain/src/OgreMaterial.cpp
OgreMain/src/OgreMesh.cpp
OgreMain/src/OgrePass.cpp
OgreMain/src/OgreRibbonTrail.cpp
OgreMain/src/OgreSceneNode.cpp
OgreMain/src/OgreTechnique.cpp
Tests/OgreMain/src/MeshSerializerTests.cpp

fix declaration and un-deprecate as applicable. Also do bounds checking
for full binding support.

Main: simplify & inline getElement(N) helper functions

---

OgreMain/include/OgreScriptTranslator.h

The error occurred when calling getTranslator(const AbstractNodePtr&) on an RTShader::SGScriptTranslatorManager in ScriptCompilerManager::getTranslator(const AbstractNodePtr&) due to the ScriptTranslatorManager not being exported. Therefore, technically, both OgreMain and OgreRTShaderSystem contain distinct ScriptTranslatorManager types.
See https://stackoverflow.com/a/57304113 and https://bugs.llvm.org/show_bug.cgi?id=39191#c1.

Fix UBSan error about member call on address not pointing to ScriptTranslatorManager

---

OgreMain/include/OgreSingleton.h

UBSan complains a lot about the this pointer not being of type T* which is correct during construction, but ultimately doesn't matter. This change disables the vptr check on the Singleton constructor to avoid errors from UBSan.

Disable vptr checks for Singleton constructor

---

OgreMain/include/OgreMath.h

Fixing the compiling error in linux, I put include in OgreMath.h as Pavel said.

fix compiling error in linux 2

---

OgreMain/src/OgreSIMDHelper.h

Fix this warning messages
[output.txt](https://github.com/OGRECave/ogre/files/6569091/output.txt)

fix warnings on compiling with GCC11 in linux

---

RenderSystems/GLES2/src/OgreGLES2HardwarePixelBuffer.cpp
RenderSystems/GLES2/src/OgreGLES2Texture.cpp

changes toString for StringUtil::format as documentation advises.

Fixing warning in a deprecated String::toString case

---

Components/RTShaderSystem/src/OgreShaderExPerPixelLighting.cpp
Components/RTShaderSystem/src/OgreShaderFFPLighting.cpp
Components/Terrain/src/OgreTerrainMaterialShaderHelperGLSL.cpp
Media/RTShaderLib/GLSL/SGXLib_PerPixelLighting.glsl

generally use ACT variant for data retrieval

RTSS: fix use of non-unit light direction when scaling is present

---

Components/RTShaderSystem/src/OgreShaderProgramManager.cpp
Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp

seems VS2019 does not like it
fixes #2134

RTSS: ProgramManager - drop superfluous cast

---

OgreMain/include/Ogre.i

SWIG: consistently name containers _type_List and _type_Map

---

Components/Overlay/src/OgreFont.cpp
Components/RTShaderSystem/src/OgreShaderProgram.cpp

Compiling errors when using the double precision.
Overlay: Non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list.
RTS: Call to constructor of 'Ogre::RTShader::UniformParameter' is ambiguous.

Fix compiling issues regarding mismatch and ambiguous between float and double.

---

CMake/Packages/FindOpenGLES2.cmake

Fixed a missing `include(FindPkgMacros)` in `FindOpenGLES2.cmake`

🐛 Fixed missing include in FindOpenGLES2.cmake

---

CMakeLists.txt

Without this small changes build on macOS fails with error like:
```
error: Objective-C was disabled in PCH file but is currently enabled
```
Here a two small changes:
- increase minimal version of cmake to 3.16.0.
- enable languages `OBJC` and `OBJCXX`;
CMake-3.16.0 was the first one which is supported `OBJC` and `OBJCXX`: https://discourse.cmake.org/t/cmake-3-16-0-available-for-download/262

Enable OBJC and OBJCXX for apple build

---

Media/RTShaderLib/GLSL/SGXLib_PerPixelLighting.glsl

Error: RTSS - creating GpuPrograms for pass 0 of 'RTSS/OffsetMapping' failed
An exception has occurred: RuntimeAssertionException: gpuProgram failed. gpu program could not be created in createGpuPrograms at /home/joilnen/ogre3d_devel/my/ogre3d-13.2.c4039/Components/RTShaderSystem/src/OgreShaderProgramManager.cpp (line 250)

Fix this crash in linux(arch linux/intel(mesa21.2.1-1)

---

CMake/Dependencies.cmake
Components/Bites/CMakeLists.txt

Use the cmake commands of
https://doc-snapshots.qt.io/qt6-dev/cmake-qt5-and-qt6-compatibility.html#supporting-older-qt-5-versions
to support both Qt 5 and Qt 6.

Use Qt 6 for OgreBitesQt if present

---

Components/Bites/include/OgreInput.h

Compiler from ndk23 complaint from this copy constructor, changed to a most common form
---
452 In file included from /home/joilnen/ogre3d_devel/my/ogre3d-13.0.x/Samples/Common/include/DefaultSamplesPlugin.h:31:
453 In file included from /home/joilnen/ogre3d_devel/my/ogre3d-13.0.x/Samples/Common/include/SamplePlugin.h:32:
454 In file included from /home/joilnen/ogre3d_devel/my/ogre3d-13.0.x/Samples/Common/include/Sample.h:42:
455 /home/joilnen/ogre3d_devel/my/ogre3d-13.0.x/Components/Bites/include/OgreInput.h:205:25: warning: definition of implicit     ↳ copy constructor for 'InputListenerChain' is deprecated because it has a user-declared copy assignment operator [-Wdepr    ↳ ecated-copy]
456     InputListenerChain& operator=(InputListenerChain o)
457                         ^ …

fix warnings in ndk23 copy constructor issues

---

OgreMain/include/OgreRenderSystemCapabilities.h
OgreMain/src/OgreRenderSystemCapabilities.cpp
OgreMain/src/OgreRenderSystemCapabilitiesSerializer.cpp
RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
RenderSystems/GL/src/OgreGLRenderSystem.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
RenderSystems/Metal/src/OgreMetalRenderSystem.mm
RenderSystems/Vulkan/src/OgreVulkanRenderSystem.cpp
Tests/OgreMain/src/RenderSystemCapabilitiesTests.cpp
Tests/OgreMain/src/UseCustomCapabilitiesTests.cpp

and clarify the unit. The type separation only made sense on D3D9.

Main: RenderSystemCapabilities - deprecate int&bool programConstantCount

---

RenderSystems/Vulkan/CMakeLists.txt
RenderSystems/Vulkan/include/OgreVulkanDevice.h
RenderSystems/Vulkan/include/OgreVulkanMappings.h
RenderSystems/Vulkan/include/OgreVulkanPrerequisites.h
RenderSystems/Vulkan/include/OgreVulkanQueue.h
RenderSystems/Vulkan/include/OgreVulkanRenderPassDescriptor.h
RenderSystems/Vulkan/include/OgreVulkanTextureGpu.h
RenderSystems/Vulkan/include/OgreVulkanUtils.h
RenderSystems/Vulkan/include/OgreVulkanWindow.h
RenderSystems/Vulkan/src/OgreVulkanDescriptorPool.cpp
RenderSystems/Vulkan/src/OgreVulkanDevice.cpp
RenderSystems/Vulkan/src/OgreVulkanHardwareBufferManager.cpp
RenderSystems/Vulkan/src/OgreVulkanQueue.cpp
RenderSystems/Vulkan/src/OgreVulkanRenderSystem.cpp
RenderSystems/Vulkan/src/OgreVulkanUtils.cpp
RenderSystems/Vulkan/src/OgreVulkanWindow.cpp
RenderSystems/Vulkan/src/volk.c
RenderSystems/Vulkan/src/volk.h
ci-build.cmake

allows targetting old Android NDKs and
deploying to environments with no vulkan

Vulkan: use dynamic function dispatch to avoid linking to libvulkan

---

OgreMain/src/OSX/OgreFileSystemLayer.cpp
RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm

It allows to build on macOS up to 10.10.
Anyway, it is uses `NSOpenGLContext.pixelFormat` which was added at 10.10 and removing it seems like as a huge and meanless job.

fixed build on old macOS

---

Components/Python/CMakeLists.txt

Try to detect the sitelib path from python instead of guessing it.
Used by openSUSE to fix packaging issues.

Python: Try to detect correct python sitelib path before guessing one

---

CMake/Dependencies.cmake
CMakeLists.txt
PlugIns/Assimp/CMakeLists.txt

This solve an issue where assimp >= 5.1 is not found by cmake, as the `package_name` is `assimp` not `ASSIMP`.
But this also updates the assimp version used for msvc builds and drops the cmake workaround for assimp 5.0, as this is fixed with 5.1.
This should be of cause discussed if dropping 5.0 support is ok, did this because then also the workaround can be dropped, but only changing the `package_name` and keep the workaround should work if 5.0 support should stay.

Assimp: Fix detection of assimp 5.1, upgrade bundled assimp, remove cmake workaround for CI

---

RenderSystems/GLSupport/src/GLX/OgreGLXGLSupport.cpp

As long as context_attrib[1] is larger than majorVersion, the minor Version must not be checked.
Fixes commit 680150caaf16632578e5e294df5dfc43eacd30fe

GLSupport: GLX - fix selecting maximal supported context version

---

OgreMain/src/OgreRenderSystem.cpp
RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp

this is a "prototype" fix for the dx11 render system and should not be checked into ogre main as it will cause leaks with non dx11 render systems.  it *does* however fix my issues with directx 11 so it's illustrative of the issue.
there are two memory leaks with the dx11 render system that cause crashes in my tools and app on shutdown.  these leaked resources appear to hold strong references to each other so basically if either of the following leaks occur some 80+ directx objects get leaked (including the top level DX11 device, etc etc).  the two issues are:
1. class D3D11RenderTexture holds a reference to a class D3D11DepthBuffer which is not always freed.
2. class D3D11DepthBuffer holds a reference to ID3D11DepthStencilView which is not always freed regardless of whether or not the …

dx11 TU_RENDERTARGET texture leak.

---

OgreMain/include/OgreWorkQueue.h

The single word in the docs startled me enough to research in the codebase.
```
WORKQUEUE_CHANGECOLLECTION_REQUEST = 3 (unused?)
WORKQUEUE_DERIVED_DATA_REQUEST = 1 ("Ogre/Terrain")
WORKQUEUE_GENERATE_MATERIAL_REQUEST = 2 ("Ogre/Terrain")
WORKQUEUE_LOAD_LOD_DATA_REQUEST = 1 ("Ogre/TerrainLodManager")
WORKQUEUE_LOAD_REQUEST = 1 ("Ogre/VolumeRendering", "Ogre/TerrainGroup")
WORKQUEUE_LOAD_TERRAIN_PAGE_REQUEST = 1 ("Ogre/TerrainPagedWorldSection")
WORKQUEUE_PREPARE_REQUEST = 1 (""Ogre/Page"")
```
Although it wouldn't make sense, it was technically possible that request types must be unique per WorkQueue instance and defining user values would need to start with some "minimum user value" constant.

Main: clarified WorkQueue request type values.

---

Components/Terrain/src/OgreTerrainMaterialShaderHelperGLSL.cpp
Media/Main/OgreUnifiedShader.h

stemming from GL_EXT_shader_explicit_arithmetic_types

UnifiedShader: use forward compatible precision declarations

---

OgreMain/src/OgreMaterial.cpp

if a loaded material is cloned, the memory size of the cloned material isn't tracked.
Quick example pseudo code:
```
matA = MaterialManager::getSingleton().create(...);
matA->load(); //adds xxx bytes to the ResourceManager::mMemoryUsage
matB = matA.clone(...); //adds nothing
matB->unload(); //removes xxx bytes from the ResourceManager::mMemoryUsage
matA->unload(); //removes xxx bytes from the ResourceManager::mMemoryUsage
```
If you do something like that, the ResourceManager::mMemoryUsage will be "negative", but it's an unsigned value so..
After that, every time ResourceManager::checkUsage(void) is called, it'll say the memory budget is exceeded.

Fixed Invalid memory usage when cloning material

---

Components/RTShaderSystem/src/OgreShaderProgramManager.cpp

Otherwise there's memory leakage.

RTSS: Delete default program processors.

---

Samples/Simple/include/Fresnel.h

Fixed ```Fresnel.h:216:48: error: invalid conversion from 'const char*' to 'Ogre::ResourceHandle' {aka 'unsigned int'} [-fpermissive]```
Also appears on the 13.3.4 tag.

Samples: Fixed compilation error.

---

OgreMain/include/OgreMaterialSerializer.h
OgreMain/src/OgreMaterialSerializer.cpp

There was a refactor where samplers were moved out of mConstants
and into mRegisters. However, the serializer still tried to access
them from mConstants, which results in either invalid data or segfaults.
This should also be backported to the 13.3.4 tag (couldn't find a branch).

Main: fixed incorrect handling of samplers as constants

---

Tests/CMakeLists.txt

See https://github.com/google/googletest/issues/3219
I got the error that's mentioned in the above issue when running with GCC 11.2.1.
Bumping gtest fixed it, but I haven't tried with any other compilers. I'm hoping the CI system will handle that.

Main: Bump GTest because of issues with gcc 11.

---

OgreMain/src/OgreStaticGeometry.cpp

Setting the rendering distance on a static geometry had
no influence whether batches were skipped while rendering.
Fixes #2427
Broken since commit 060f9705c35b7278a89e03d5daf47b50e36cc319

Main: fix StaticGeometry::setRenderingDistance

---

CMakeLists.txt

This is [currently breaking]( https://buildd.debian.org/status/fetch.php?pkg=mygui&arch=mipsel&ver=3.2.0-1&stamp=1365373881&raw=0 ) the Debian build on MIPSLE

Don't use sse on non-x86 architectures

---

OgreMain/src/OgreInstanceBatchHW.cpp

essential to get DISCARD on D3D9. About 5% benefit for the others.
before/ after (fps at 10k instances)
-    D3D9: 158/270
-    GL3+: 260/280
-    D3D11: 290/305

Main: InstanceBatchHW - use correct HBU_CPU_TO_GPU

---

BuildingOgre.md

Thank you to the maintainers and contributors of this library. This PR is just a small fix in the installation instructions for Ubuntu.
CMake fails while following BuildingOgre.md when only the necessary packages are installed (and no recommended optional packages):
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xrandr_LIB (ADVANCED)
Simply installing the missing ``libxrandr`` via apt fixes the issue.
``libxrandr`` is listed as a dependency of [libsdl2-dev](https://packages.ubuntu.com/jammy/libsdl2-dev) (a recommended package), so the issue would have not been visible in CI that installs the recommended packages.

Make libxrandr-dev a requirement for Ubuntu

---

PlugIns/OctreeZone/src/OgreOctreeZone.cpp
PlugIns/PCZSceneManager/include/OgrePortalBase.h
PlugIns/PCZSceneManager/src/OgreDefaultZone.cpp
PlugIns/PCZSceneManager/src/OgrePortalBase.cpp

On the PCZSceneManager docs (https://github.com/OGRECave/ogre/tree/master/PlugIns/PCZSceneManager) it says: "NOTE: Scaling of a portal is not yet tested. Scaling a node should scale the portal (but don't cry to me if it doesn't work right yet...)"
I have scaling in my PCZ Scene. Culling works correctly through scaled portals. However, Nodes passing through Portals (and other intersections) were tested against unscaled radii. This PR fixes that.

PCZSceneManager: fix scaling of portal radius

---

OgreMain/src/OgreTexture.cpp

We're currently trying to [upgrade from Ogre1.12.1 to Ogre1.12.10](https://github.com/ros2/rviz/pull/878) and have encounterered some tests failing, which I believe is due to a bug introduced in #1755.
Before the changes in #1755 of refactoring the ``Texture::convertToImage(Image& destImage, bool includeMipMaps)`` method, no mipmaps were generated with the example below, but since 1.12.10 onwards, one extra mipmap gets generated.
Here is a minimal example to reproduce the issue on 1.12.10 and beyond:
**main.cpp**
```cpp
#include <OgreImage.h>
#include <OgreResourceGroupManager.h>
#include <OgreTextureManager.h>
#include <OgreTexture.h>
#include <OgreApplicationContext.h>
#include <OgreRoot.h>
#include <iostream>
class MyTestApp : public OgreBites::ApplicationContext
{
public:
MyTestApp() …
```

Bug: One extra mipmap being generated in Ogre::Texture::convertToImage

---

OgreMain/src/OgreLight.cpp
Tests/OgreMain/src/General.cpp
Tests/OgreMain/src/QuaternionTests.cpp

fixes #2648 and also makes some changes to tests so that they run successfully with Real as double.

Main: fix compilation for Real=double and affected tests

---

OgreMain/src/OgreMeshSerializerImpl.cpp
OgreMain/src/OgreMeshSerializerImpl.h

- read/ write methods handle Real=double conversion for us
- some calc*Size methods dont need an argument

Main: slightly clean up MeshSerializerImpl

---

OgreMain/src/OgreFrustum.cpp

The Matrix4 constructor taking a Quaternion is now explicit, so explicit conversion was required in this case.

Fix the build

---

RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp

The problem was in this line:
ConfigOptionMap::const_iterator end = mGLSupport->getConfigOptions().end();
and in this one:
if ((opt = mGLSupport->getConfigOptions().find("Orientation")) != end)
Because getConfigOptions() returns a container by value, that container is destroyed immediately after we take an iterator to it. Then we use that iterator after it's container has been destroyed.
This problem was reported by Clang as a warning.

Fix access to an iterator after its container has beed destroyed

---

RenderSystems/Direct3D9/src/OgreD3D9Texture.cpp

as the actual num mips is now always capped. Fixes cubemaps on D3D9.

D3D9: we must check num requested mips against MIP_UNLIMITED

---

Components/RTShaderSystem/src/OgreShaderProgramManager.cpp

It seems to be possible that the result of std::find in this context is the 'end' iterator. So I added a check.

Check the result of std::find to prevent erasing 'end' iterator

---

OgreMain/include/OgrePrerequisites.h
OgreMain/include/OgreVector.h
Tests/OgreMain/src/General.cpp

OSX seems particularly picky here

Main: correctly export typeinfo for Vector

---

Components/Overlay/include/OgreFont.h

Issue:
Trying to display a non-ASCII symbol in the Overlay GUI results in an exception thrown from underneeth Ogre::Root::renderOneFrame().
Solution:
Make Ogre::Font::getGlyphInfo() return the information for the fallback '?' character when the requested character is missing from the font. Since the glyph information also contains the UV coordinates of the character, this change is enough to display question marks in place of characters missing from the font.

Implement a fallback for Ogre::Font::getGlyphInfo()

---

RenderSystems/GLES2/include/EAGL/OgreEAGL2View.h

That directive was causing an ambiguous name lookup for name "Rect" on iOS.

Remove "using namespace Ogre" from a header

---

Components/Terrain/src/OgreTerrainRTShaderSRS.cpp

Terrain: make sure we also generate texcoords when compression is off

---

OgreMain/src/OgreShadowRenderer.cpp

In the method SceneManager::ShadowRenderer::destroyShadowTextures, the camera cam is destroyed and then cam->getCullingFrustrum() is called on the already destroyed object, which results in a crash if the memory at that location gets reused (or cleaned by gdb, which is how i found this bug).

ShadowRenderer: Fix useAfterFree bug when destroying shadow textures

---

RenderSystems/GLSupport/src/win32/OgreWin32GLSupport.cpp

Old code produced '4.3' for OpenGL 4.1 (_VMware 16.2.5_).
Regression from f9bf70d8e4b3c3d6e2cb6f9f2cacf98e8312d22c

GLSupport: fix requested version of GL context

---

OgreMain/include/OgreAnimationState.h

The deprecated function `AnimationStateIterator getAnimationStateIterator(void);` is missing the OGRE_DEPRECATED modifier.

Minor: Adds missing OGRE_DEPRECATED modifier

---

RenderSystems/GLSupport/src/EGL/X11/OgreX11EGLWindow.cpp

GLSupport: EGL - always derive new config on X11

---

Components/RTShaderSystem/src/OgreShaderGLSLProgramWriter.cpp

This fixes that the vertex shader compilation would fail with error "'array without size' :  supported in geometry shaders only" on an Intel HD Graphics 4000 integrated video chip. This fix was already done in GLSLShader::compileSource 5 years ago with https://github.com/OGRECave/ogre/commit/d8d99cecf260e0441f77e6a1b1ceceea5e934ac7.

Use a workaround for gl_ClipDistance on Intel Windows drivers.

---

CMake/Dependencies.cmake

Building dependencies like SDK2 and assimp currently takes an unnecessary long time, because they do not use all available processor cores. With this patch, the number of available cores is automatically detected and passed to the dependency CMake scripts. This makes the build process about 2-3 times faster on my 12 Core processor when using MinGW-w64.

Use all available processor cores to build dependencies

---

RenderSystems/GL3Plus/src/OgreGL3PlusStateCacheManager.cpp

VAO's are otherwise never deleted

Delete the VAO regardless

---

Tests/VisualTests/CMakeLists.txt

I get the following error when I build ogre for  Arch Linux RISC-V:
```
ninja: Entering directory `build'
[0/1] Running tests...
Test project /build/ogre/src/ogre-13.5.3/build
Start 1: TestContext_OpenGLRenderingSubsystem
1/2 Test #1: TestContext_OpenGLRenderingSubsystem ........***Timeout 1500.09 sec
Start 2: TestContext_OpenGLES2.xRenderingSubsystem
2/2 Test #2: TestContext_OpenGLES2.xRenderingSubsystem ...   Passed  876.72 sec
50% tests passed, 1 tests failed out of 2
Total Test time (real) = 2376.84 sec
The following tests FAILED:
1 - TestContext_OpenGLRenderingSubsystem (Timeout)
Errors while running CTest
```
It takes about 3000s to pass `TestContext_OpenGLRenderingSubsystem` on a HiFive Unmatched board. Passed the test and built successfully after extending the timeout.
```
ninja: …
```

Avoid CTest timeout for RISC-V

---

RenderSystems/Direct3D9/src/OgreD3D9Mappings.cpp

as most D3D9 implementations do anyway

D3D9: fall back to SO_GOURAUD for SO_PHONG

---

RenderSystems/GL/src/OgreGLRenderSystem.cpp

Corrects the use of the mCurrentContext pointer when it points to null.  
—————————————
Corrige l'utilisation du pointeur mCurrentContext alors qu'il pointe sur nul.
See:
https://forums.ogre3d.org/viewtopic.php?p=554471#p554471

[GL]mCurrentContext is null

---

OgreMain/include/OgreAnimationTrack.h
OgreMain/src/OgreAnimationTrack.cpp

motivation: https://forums.ogre3d.org/viewtopic.php?p=554574

Main: setTransformSpace() on NodeAnimationTrack

---

OgreMain/include/OgreCamera.h
OgreMain/include/OgreFrustum.h
OgreMain/include/OgreLight.h
OgreMain/include/OgreMovablePlane.h
OgreMain/include/OgrePrerequisites.h
OgreMain/src/OgreCamera.cpp
OgreMain/src/OgreFrustum.cpp
OgreMain/src/OgreInstanceBatch.cpp
OgreMain/src/OgreInstancedEntity.cpp
OgreMain/src/OgreMovablePlane.cpp
OgreMain/src/OgreSceneManager.cpp
OgreMain/src/OgreSimpleRenderable.cpp
OgreMain/src/OgreStaticGeometry.cpp
PlugIns/OctreeSceneManager/src/OgreOctreeSceneQuery.cpp
PlugIns/PCZSceneManager/src/OgrePCZSceneQuery.cpp
Samples/ShaderSystem/src/ShaderSystem.cpp

Fixes [this issue](https://forums.ogre3d.org/viewtopic.php?t=96994) for a couple more MovableObjects. Also uses the MOT_* constants instead of comparing against literals.

MOT_* strings for all MovableObjects

---

OgreMain/include/OgreDefaultDebugDrawer.h
OgreMain/include/OgreSceneManager.h
OgreMain/src/OgreDefaultDebugDrawer.cpp
OgreMain/src/OgreEntity.cpp

I needed this for my project. It seems to work and thought it might be useful for others. However…
The docs say that Node::_getFullTransform() “should only be called by a SceneManager which knows the derived transforms have been updated before calling this method.” I do not know if that is the case when Entity::_updateRenderQueue() is called. Please advise.
The DefaultDebugDrawer::drawAxes() size parameter could come from DefaultDebugDrawer or from Entity. Rather than add a debug data member to every Entity I thought it better to have it in just the DefaultDebugDrawer. However that means to set the value, we either have to change SceneManager’s interface, or just cast the return of SceneManager::getDebugDrawer() to a DefaultDebugDrawer *, which is what I’m doing.
Not sure about my design …

DefaultDebugDrawer: transform bones and set axes size

---

OgreMain/src/OgreResourceGroupManager.cpp

On application close the ResourceGroupManager::_notifyAllResourcesRemoved is called which removes all resources from the loadResourceOrderMap.
When we erase the resource from the container the resource can be deleted (if the use-counter = 0). In this case D3D9HLSLProgram d-tor is called which tries to unload its resources (HighLevelGpuProgram::unloadImpl) and it calls ResourceGroupManager::_notifyResourceRemoved. This method removes these resources from the same container what we are operating above which invalidates our iterator and we crash.

ResourceGroupManager shutdown crash

---

OgreMain/include/OgreHardwareBuffer.h
OgreMain/include/OgreHardwareIndexBuffer.h
OgreMain/include/OgreHardwarePixelBuffer.h
OgreMain/include/OgreHardwareVertexBuffer.h
OgreMain/src/OgreDefaultHardwareBufferManager.cpp
OgreMain/src/OgreHardwareIndexBuffer.cpp
OgreMain/src/OgreHardwarePixelBuffer.cpp
OgreMain/src/OgreHardwareVertexBuffer.cpp
RenderSystems/Direct3D11/src/OgreD3D11HardwareBuffer.cpp
RenderSystems/Direct3D11/src/OgreD3D11HardwarePixelBuffer.cpp
RenderSystems/Direct3D9/src/OgreD3D9HardwareBuffer.cpp
RenderSystems/Direct3D9/src/OgreD3D9HardwarePixelBuffer.cpp
RenderSystems/GL/src/OgreGLHardwareBuffer.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusHardwareBuffer.cpp
RenderSystems/GLES2/src/OgreGLES2HardwareBuffer.cpp
RenderSystems/GLSupport/src/OgreGLHardwarePixelBufferCommon.cpp
RenderSystems/Metal/src/OgreMetalHardwareBufferCommon.mm
RenderSystems/Metal/src/OgreMetalHardwarePixelBuffer.mm
RenderSystems/Tiny/src/OgreTinyHardwarePixelBuffer.cpp
RenderSystems/Vulkan/src/OgreVulkanHardwareBuffer.cpp
RenderSystems/Vulkan/src/OgreVulkanTextureGpu.cpp

it was obsoleted when shadow buffers were introduced

Main: HardwareBuffer - get rid of unused isSystemMemory flag

---

Docs/src/ogre-shadows.md

As I mentioned in this [forum thread](https://forums.ogre3d.org/viewtopic.php?t=97082), this tutorial uses code that cannot compile since [setShadowTextureCasterMaterial](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_scene_manager.html#aa22c0af6835b4a0524b4122756cdd93c) does not accept strings. Thus, I added `MaterialManager::getByName` to get the `MaterialPtr` which it required. 
Additionally, I added a paragraph near the beginning explaining that the tutorial is more in depth than in needed just to have shadows in OGRE, so that people reading it aren't mislead if they just want to add shadows to their scene, since the tutorial is quite old.

docs: fix shadow tutorial code example

---

Docs/src/high-level-programs.md
Docs/src/material-scripts.md
Docs/src/ogre-shadows.md
Docs/src/scripts.md

this pull request does two things:
1. adds .overlay to the list files of searched for scripts (placed at the end as it appears to be by my testing)
2. adds the basics of declaring and referencing tessellation and compute scripts to material and GPU program pages. 
If I understand the git message correctly, it also adds terminal new lines to the end of text files I edited. If this is a problem, I can look into suppressing this behaviour in my editor.

docs: update scripting manual

---

Docs/src/manual.md
Docs/src/scripts.md

Expand and clarify the documentation for overlays. In particular, emphasizing the need to register the OverlaySystem, since this was what I missed when I was trying to get them working.

Docs: clarify using Overlays from .overlay files

---

CMake/Packages/FindCg.cmake
CMake/Packages/FindDirectX.cmake
CMake/Packages/FindDirectX11.cmake
CMake/Packages/FindSoftimage.cmake
CMakeLists.txt
OgreMain/CMakeLists.txt

Instead of using `CMAKE_CL_64`, we should be using `CMAKE_SIZEOF_VOID_P`.
In the official CMAKE documentation it says that `CMAKE_CL_64` is deprecated (https://cmake.org/cmake/help/latest/variable/CMAKE_CL_64.html)
And the 64-bit detection does not work in `MinGW64`.

CMAKE_CL_64 is deprecated and only works with Microsoft Visual Studio

---

RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm

instead of silently failing
related #2923

GLSupport: OSX - throw on broken createNewWindow code path

---

PlugIns/Assimp/src/AssimpLoader.cpp

Fixes the imported model animations from the Assimp plugin.
before|after
-|-

fix: Assimp importer animations

---

OgreMain/include/OgreParticleAffectorFactory.h
OgreMain/include/OgreParticleEmitterFactory.h
OgreMain/src/OgreParticleEmitter.cpp
OgreMain/src/OgreParticleSystem.cpp
PlugIns/ParticleFX/include/OgreTextureAnimatorAffector.h
PlugIns/ParticleFX/src/OgreBoxEmitterFactory.h
PlugIns/ParticleFX/src/OgreColourFaderAffectorFactory.h
PlugIns/ParticleFX/src/OgreColourFaderAffectorFactory2.h
PlugIns/ParticleFX/src/OgreColourImageAffectorFactory.h
PlugIns/ParticleFX/src/OgreColourInterpolatorAffectorFactory.h
PlugIns/ParticleFX/src/OgreCylinderEmitterFactory.h
PlugIns/ParticleFX/src/OgreDeflectorPlaneAffectorFactory.h
PlugIns/ParticleFX/src/OgreDirectionRandomiserAffectorFactory.h
PlugIns/ParticleFX/src/OgreEllipsoidEmitterFactory.h
PlugIns/ParticleFX/src/OgreHollowEllipsoidEmitterFactory.h
PlugIns/ParticleFX/src/OgreLinearForceAffectorFactory.h
PlugIns/ParticleFX/src/OgrePointEmitterFactory.h
PlugIns/ParticleFX/src/OgreRingEmitterFactory.h
PlugIns/ParticleFX/src/OgreRotationAffectorFactory.h
PlugIns/ParticleFX/src/OgreScaleAffectorFactory.h

this is redundant with ParticleSystem and slows down clearing due to O(N) lookup and erase

Main: ParticleSystem - do not track Affectors and Emitters in Factories

---

OgreMain/src/OgreWorkQueue.cpp

Fix processMainThreadTasks() logic

---

OgreMain/include/OgrePrerequisites.h
OgreMain/src/OgreFrustum.cpp

I introduced a spelling error (frustrum instead of frustum) with [this](https://github.com/OGRECave/ogre/pull/2842) commit. Hopefully fixing it isn't too breaking. I doubt many people have tested for frustums since 14 came out and updating any broken code should be trivial.

Main: fix spelling error

---

OgreMain/include/OgreSceneNode.h
OgreMain/src/OgreSceneNode.cpp
Tests/OgreMain/src/General.cpp

This commit adds convenience method to delete a node and its attached objects, as I needed and people asked about [here](https://forums.ogre3d.org/viewtopic.php?t=28547) and [here](https://forums.ogre3d.org/viewtopic.php?t=53647). 
The use case is if you want to clear a `SceneNode` and put everything back from scratch (a simple if slower way of updating an object to reflect game state), or if you wish to stop rendering a node (and thus things attached to it can be garbage collected). 
This patch adds three new non-virtual methods to `SceneNode` that analogous to the other methods but also delete the detached objects:
`SceneNode::destroyGraphSegment`, analogous to `SceneNode::removeAndDestroyAllChildren`, except it also destroys all MovableObjects attached to `this` and to any of the …

add SceneNode deletion convenience methods

---

RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp

This patch turns on normalized access to `VET_INT_10_10_10_2_NORM` vertex attributes under the GLES2 backend.
Every other RS that supports this format enables normalized access ([1][2][3]) and the `_NORM` suffix implies that it should be normalized, so maybe it was just not tested with GLES2.
[1] https://github.com/OGRECave/ogre/blob/6ee8101f0b72f31ba31697866f4d91a217354c35/RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp#L1685-L1686
[2] https://github.com/OGRECave/ogre/blob/6ee8101f0b72f31ba31697866f4d91a217354c35/RenderSystems/Vulkan/src/OgreVulkanMappings.cpp#L206-L207
[3] https://github.com/OGRECave/ogre/blob/6ee8101f0b72f31ba31697866f4d91a217354c35/RenderSystems/Metal/src/OgreMetalMappings.mm#L345

GLES2: turn on normalization for VET_INT_10_10_10_2_NORM

---

OgreMain/include/Ogre.i
OgreMain/include/OgreSceneManager.h
OgreMain/src/OgreSceneManager.cpp

Added access to the full map of names to StaticGeometry held by the SceneManager.
Renamed the internal typedef `StaticGeometryList` to `StaticGeometryMap` to make it similar to `MoveableObjectMap` as I made it public but I didn't renamed the internal `mStaticGeometryList`.

Static Geometry collection access in scenemanager (fixes #113)

---

Tests/OgreMain/src/General.cpp
Tests/VisualTests/PlayPen/include/PlayPenTests.h
Tests/VisualTests/PlayPen/src/PlayPenTestPlugin.cpp
Tests/VisualTests/PlayPen/src/PlayPenTests.cpp

Tests: convert BillboardTextureCoords VTest to Unit Test

---

CMake/Dependencies.cmake

While I was compiling the source code in CMake, the application gave me an error message saying that it could not find zlib's source code. Therefore, I changed the original link (located in the _Dependencies.cmake_ file) with the original release located on GitHub. Everything now works just fine.

CMake : Dependencies - updated zlib's broken link

---

CMake/Dependencies.cmake
Components/Bullet/CMakeLists.txt

Just a check before downloading bullet making sure the user is interested in building the ogre bullet module since otherwise bullet would not really be considered strictly necessary  unlike sdl for example.

Changes in CMake files to avoid downloading bullet when it is not needed

---

OgreMain/src/OgreGpuProgramManager.cpp

as we changed the disk format for D3D11 in 14.2
fixes  #3056

Main: GpuProgramManager - bump Microcode cache version

---

OgreMain/src/OgreShadowRenderer.cpp

To avoid segfault.
This could happen if the shadow caster material isn't loaded, or if it doesn't contain any valid techniques.

Main: ShadowRenderer - check that tech and pass exists

---

RenderSystems/GL3Plus/src/OgreGL3PlusPixelFormat.cpp

variable `format` 's type is `PixelFormat`, it shouldn't compared to `GL_NONE`.
it  is  mismatched.
i change it to `GLformat`

fix mismatch operand type for operator ==

---

CMakeLists.txt

Fix typo in the comments of  CMakeLists.txt

Fix: typo in comments of  CMakeLists.txt

---

PlugIns/DotScene/include/OgreDotSceneLoader.h
PlugIns/DotScene/misc/dotscene.dtd
PlugIns/DotScene/src/DotSceneLoader.cpp

Rectangular Area Lights were added in OGRE 14.1, but they are not loaded by DotScene.
https://www.ogre3d.org/2023/09/12/ogre-14-1-released#rectangular-area-lights

Add support for LT_RECTLIGHT to DotScene

---

OgreMain/src/OgreLog.cpp

Main: Log - spell out %T as MinGW does not support %T

---

PlugIns/DotScene/misc/dotscene.dtd
PlugIns/DotScene/src/DotSceneLoader.cpp

This option is being used in `DotSceneLoader.cpp` but is absent in the DTD.

Remove improper "active" attribute from skyBox in DotSceneLoader

---

OgreMain/src/OgreMovableObject.cpp

if object was not visible, this could have triggered infinite technique additions via _arbitrateMissingTechniqueForActiveScheme
fixes #3084

Main: MovableObject - getReceivesShadows does not need best technique

---

Components/Overlay/src/OgreFont.cpp

If HAVE_FREETYPE macro is not defined, the memory allocated in buffer is not freed

Font: Memory leak

---

OgreMain/src/OgreGpuProgramParams.cpp

for single element types. Multi element types are always float.

Main: GpuProgramParameters - assert correct constant type

---

CMake/Templates/OGRE-BitesQt.pc.in
Components/Bites/CMakeLists.txt

This work adds OGRE-BitesQt.pc.in template file and necessary cmake commands to configure and install it, if applicable. 
Note that the commands are not placed in `ConfigureBuild.cmake` as most (or all) the other pkgconfig configurations are done. The reason for doing it in `Component/Bites/CMakeLists.txt` is that some necessary variables are not defined earlier.
I assume most people use OGRE's find package script over pkgconfig, since this has not been reported. Nevertheless, it is useful to provide it for completeness.

Add missing OGRE-BitesQt pkgconfig file

---

RenderSystems/GLSupport/include/EGL/Wayland/OgreWaylandEGLSupport.h
RenderSystems/GLSupport/include/EGL/Wayland/OgreWaylandEGLWindow.h
RenderSystems/GLSupport/src/EGL/OgreEGLSupport.cpp
RenderSystems/GLSupport/src/EGL/Wayland/OgreWaylandEGLSupport.cpp
RenderSystems/GLSupport/src/EGL/Wayland/OgreWaylandEGLWindow.cpp

There are some problems with Wayland initialization:
* An assertion fails, and the list of EGL extensions contains all client extensions twice and none of the display extensions, because WaylandEGLSupport::start() is called when mGLDisplay has not yet been set.
* GLNativeSupport::mFSAAlevels is duplicated every time a WaylandEGLWindow is created, because of the WaylandEGLSupport::doInit() call in WaylandEGLWindow::create().
* The wl_surface is stored in WaylandEGLSupport, but each WaylandEGLWindow should be able to have its own wl_surface.
I changed WaylandEGLSupport::start() to only print a message, and delayed the EGL initialization to the first time WaylandEGLSupport::newWindow() is called. This is similar to the way Win32GLSupport handles initialization.
I also fixed some minor errors …

Improve Wayland initialization

---

Components/RTShaderSystem/src/OgreShaderFFPLighting.cpp

The RTShaderSystem only looks at specular colour and shininess when it checks whether specular lighting should be enabled or not. When specular is set to track the vertex colour in a material script, the actual colour value is still black, so specular lighting is disabled. I added an extra check to fix this.
It would also be possible to set the specular colour to white in the script translator if vertex colour tracking is enabled, but that might have other side effects.

RTShader: Enable specular lighting when vertex colours are tracked

---

Components/Bites/src/OgreApplicationContextSDL.cpp

OgreBites fails to compile if SDL is not built with both Wayland and X11 support. wmInfo.info.wl and wmInfo.info.x11 only exist if SDL supports Wayland and X11 respectively.

OgreBites: Check whether SDL supports Wayland and X11

---

RenderSystems/GL/include/OgreGLFBORenderTexture.h
RenderSystems/GL/include/OgreGLFrameBufferObject.h
RenderSystems/GL/src/OgreGLFBORenderTexture.cpp
RenderSystems/GL/src/OgreGLFrameBufferObject.cpp
RenderSystems/GL3Plus/include/OgreGL3PlusFBORenderTexture.h
RenderSystems/GL3Plus/include/OgreGL3PlusFrameBufferObject.h
RenderSystems/GL3Plus/src/OgreGL3PlusFBORenderTexture.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusFrameBufferObject.cpp
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
RenderSystems/GLES2/include/OgreGLES2FBORenderTexture.h
RenderSystems/GLES2/include/OgreGLES2FrameBufferObject.h
RenderSystems/GLES2/src/OgreGLES2FBORenderTexture.cpp
RenderSystems/GLES2/src/OgreGLES2FrameBufferObject.cpp
RenderSystems/GLSupport/include/OgreGLRenderTexture.h
RenderSystems/GLSupport/src/OgreGLRenderTexture.cpp

A shared renderbuffer might contain data from other FBO's, this is fine as long as all viewports have clearEveryFrame=true. When any viewport has clearEveryFrame=false, data would get unintentionally combined.
This fixes #3158

RenderSysten_GL: Prevent using a shared FBO renderbuffer if necessary

---

RenderSystems/GLSupport/src/EGL/Wayland/OgreWaylandEGLWindow.cpp

I noticed that FSAA was always enabled in Wayland, even if I specified FSAA == 0 in miscParams. EGL_SAMPLE_BUFFERS was always 1, so only EGLConfigs with more than 0 samples were considered.

Don't force FSAA in Wayland

---

RenderSystems/GLSupport/src/EGL/Wayland/OgreWaylandEGLWindow.cpp

so we dont accidentally get a 10 10 10 2 HDR buffer

GLSupport: set default maxBufferSize=24

---

RenderSystems/Direct3D11/include/OgreD3D11HLSLProgram.h
RenderSystems/Direct3D11/src/OgreD3D11HLSLProgram.cpp

Fix crash due to accessing freed memory in Dx11 HLSL program class.
Min repro case:
1. compile a D3D11HLSLProgram based shader via prepare().
2. trigger an unload while state=LOADSTATE_PREPARED.  (see Resource::unload () snip below)
3. this calls unprepareImpl() which *only* frees the cached string data and NOT the other 8 or so std::vectors.
4. call prepare() again. the program will crash due while iterating the std::vector data containing freed strings.
Resource::unload(void) calls either unprepareImpl() or unloadImpl () depending on the 'old' load state of a shader program.
if (old==LOADSTATE_PREPARED) {
unprepareImpl();
else
unloadImpl();

fix crashes when reusing a Dx11 program pointer.  

---

OgreMain/src/OgreControllerManager.cpp

More details: https://forums.ogre3d.org/viewtopic.php?t=97339

fix crash in the ControllerManager::updateAllControllers when mControllers is changed while iterating over it

---

Docs/src/high-level-programs.md
RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
Samples/Media/materials/programs/GLSL400/MeshProgram.glsl

to give room for meshlet buffers. Also UBOs work now with gl_spirv

GL3Plus: offset mesh SSBO binding by 3

---

Docs/src/tutorials/numpy.md
OgreMain/include/Ogre.i

SWIG: Python - allow releasing the GIL during swapBuffers

---

OgreMain/include/OgreRenderSystem.h
RenderSystems/GLSupport/src/EGL/Android/OgreAndroidEGLWindow.cpp

On android, i'm using SDL for create window
But without this, app will be crash, because SDL already created surface, so just get the surface from current

Fix get current surface for Android if use SDL

---

OgreMain/include/OgrePrerequisites.h
OgreMain/include/OgreRoot.h

triggers LNK2019 on Ogre::DebugBuild::Root
fixes #455

Main: add debug build guard on Ogre::Root

---

Docs/src/high-level-programs.md

and some smaller formatting fixes

Docs: Manual - add note about vs_2_0 aliasing on D3D11

---

CMakeLists.txt

no PDB files are generated by CMake for static libs
fixes #3260

CMake: disable PDB installation on static build

---

OgreMain/src/OgreTexture.cpp

If the method is called with includeMipMaps = FALSE or if the Texture has only one/primary mipmap in that case numMips = 0. Therefore the code just creates an empty Ogre::Image without filling its content.

Fixed Texture::convertToImage mipmap cycle.

---

OgreMain/include/OgreTexture.h
RenderSystems/Direct3D11/include/OgreD3D11Texture.h
RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp

dropped Flush as you can get the device via getCustomAttribute("D3DDEVICE") and flush yourself

D3D11: _create2DTex() from shared surface.

---

RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp

Compressed texture can't have mipmaps beyond size 4x4, so remove the last two (2x2, 1x1). However the caller can have images which does not have the full mipmaps chain or already removed the last two mipmaps. The code unconditionally removed the last mipmaps which can be useful.

D3D11Texture DDS mipmap truncation issue

---

OgreMain/include/OgreCodec.h
OgreMain/src/OgreDDSCodec.cpp
OgreMain/src/OgreDDSCodec.h

The DDSCodec keeps the DXT format if the hardware supports it. However using this stack object it is possible to enforce the DXT decompression into RGB(A) format. This is useful e.g. when we have DDS texture without mipmaps and we need them. DirectX11 does not generate mipmaps if the texture is compressed (DirectX9 does it automatically).
Also added support to obtain the DDS stream (not only saving to file).

Force the DDS/DXT stream decompression.

---

Components/Terrain/include/OgreTerrain.i

SWIG created a generic type for TerrainSlotMap; this apparently fixes it to the right type.

fix: SWIG binding TerrainSlotMap.

---

Components/Terrain/include/OgreTerrain.i
OgreMain/include/Ogre.i

Templates to fix C# swig bindings.

fix: RegionMap, LODBucketList, MaterialBucketMap and GeometryBucketList C# SWIG bindings.

---

OgreMain/include/OgreColourValue.h
OgreMain/src/OgreColourValue.cpp
Samples/ShaderSystemTexturedFog/src/RTShaderSRSTexturedFog.cpp

This fixes the initialization-order-fiasco for static colour constants while preserving API (though breaking ABI) through the following steps:
* Make `constexpr` the OgreColourValue constructor
* Instantiate global constexpr variables in a hidden namespace in `.cpp` file
* Change static class constants to references (ABI break) and assign to global `constexpr` variables
This matches the approach taken with similar static constants in gazebosim/gz-math#283.
Reference:
- https://abseil.io/tips/140
- https://en.cppreference.com/w/cpp/language/initialization

Use constexpr for static colour constants

---

OgreMain/include/OgreParticleSystem.h
OgreMain/src/OgreParticleSystem.cpp

reordering is needed for language bindings when
target language has no multiple inheritance

Main: ParticleSystem - reorder base classes and fix casts

---

OgreMain/include/OgreVector.h
OgreMain/src/OgreVector.cpp

This fixes the initialization-order-fiasco for static Vector constants while preserving API (though breaking ABI) through the following steps:
* Make `constexpr` the `VectorBase` and `Vector` constructors
* Instantiate global `constexpr` variables in a hidden namespace in .cpp file
* Change static class constants to references (ABI break) and assign to global `constexpr` variables
This matches the approach taken in #3313. Note that the `Vector(T)` constructor could not be made `constexpr`, so the `ZERO` and `SCALE` variables were constructed with repeated arguments instead of a single argument.

Use constexpr for static Vector constants

---

Components/Bullet/src/OgreBullet.cpp

getContactPoint() was using the i variable instead of the j variable which was meant to be used to refer to the contact point index.
fixes #3320

OgreBullet - Fixed wrong variable being used in onTick

---

OgreMain/src/OgreAnimationTrack.cpp

when AnimationTrack has no keyframes. The parent animation can still have keyFrameTimes.
fixes #3354

Main: AnimationTrack - use integer comparison to avoid overflow

---

Components/Bullet/include/OgreBullet.h
Components/Bullet/src/OgreBullet.cpp

btCompoundShape allows to create more than 1 collider per body. Additionally it is the only way to offset colliders against body.
Additionally allow creation of Trimesh and ConvexHull colliders out of creating RigidBody. This will help filling-up btCompoundShape, for example.
Related to #3358

OgreBullet: Support btCompound shape; collider creation

---

Components/Bullet/include/OgreBullet.h
Components/Bullet/src/OgreBullet.cpp

OgreBullet: This implements kinematic motion for a character-like movable thing.
To use one needs the following code:
```c++
mGhostObject = new btPairCachingGhostObject();
mCollisionShape = new btCompoundShape;
mGhostObject->setCollisionShape(mCollisionShape);
{
btVector3 inertia(0, 0, 0);
btScalar height = 1.0f;
btScalar radius = 0.3f;
btCapsuleShape *shape = new btCapsuleShape(radius, 2 * height - 2 * radius);
btTransform transform;
transform.setIdentity();
transform.setOrigin(btVector3(0, 1, 0));
static_cast<btCompoundShape *>(mCollisionShape)->addChildShape(transform, shape);
btScalar masses[1] = {0};
btTransform principal;
static_cast<btCompoundShape *>(mCollisionShape)->calculatePrincipalAxisTransform(masses, principal, inertia);
} …
```

Kinematic motion

---

Components/Overlay/CMakeLists.txt
Components/Overlay/include/ImGui.i
Components/Overlay/src/OgreImGuiOverlay.cpp

and make API compatible with imgui 1.92.
But dont upgrade yet as the visible fallout is too large for Ogre 14.x

Overlay: update imgui to 1.91.9b

---

RenderSystems/Vulkan/src/OgreVulkanTextureGpu.cpp

Vulkan: fix blitFromMemory for non consecutive src

---

OgreMain/include/OgreSubEntity.h

Since commit 8ba535d1485c84d819fb8e6ade0f5b59155e76b4 there is a missing include for OgreEntity.h
Furthermore, remove unused header.

Main: add missing include in OgreSubEntity

---

Components/Bullet/include/OgreBullet.h
Components/Bullet/src/OgreBullet.cpp

OgreBullet's debug rendering for physics leaves a lot to be desired regarding performance. Heightmap colliders are dense enough to put whole rendering to crawl and be unusable.
CF_DISABLE_VISUALIZE_OBJECT flag allows to exclude objects from debug rendering which is used here to remove heightmap colliders from being drawn.
By discussion I add parameter which allows enabling heightmap collider
debug anyway while it is being disabled by default.
References #3387

[OgreBullet] Remove heightmap colliders from visualization
