OGRECave/ogre

- OgreMain/include/OgreVector3.h
- Tests/OgreMain/include/QuaternionTests.h
- Tests/OgreMain/src/QuaternionTests.cpp
- Tests/OgreMain/src/VectorTests.cpp
and add unit tests for these functions.
> Improve Vector3::perpendicular() and Vector3::getRotationTo()

- OgreMain/include/OgreResourceGroupManager.h
- OgreMain/src/OgreResourceGroupManager.cpp
> ResourceGroupManager: not not use std::list* - its pointless

- Components/Bites/include/OgreTrays.h
- Components/Bites/src/OgreSGTechniqueResolverListener.cpp
- Components/RTShaderSystem/include/OgreRTShader.i
- Components/RTShaderSystem/include/OgreShaderFFPTexturing.h
- Components/RTShaderSystem/include/OgreShaderGenerator.h
- Components/RTShaderSystem/src/OgreShaderFunctionAtom.cpp
- Components/RTShaderSystem/src/OgreShaderGenerator.cpp
- OgreMain/include/OgreGpuProgramManager.h
- OgreMain/include/OgreResourceGroupManager.h
- OgreMain/src/OgreGpuProgramUsage.cpp
- OgreMain/src/OgreMaterialSerializer.cpp
- OgreMain/src/OgreSceneManager.cpp
- OgreMain/src/OgreScriptTranslator.cpp
- OgreMain/src/OgreShadowVolumeExtrudeProgram.cpp
- Samples/BezierPatch/include/BezierPatch.h
- Samples/Browser/include/SampleBrowser.h
- Samples/Python/sample.py
- Samples/ShaderSystem/src/ShaderSystem.cpp
> RTSS: add strict mode

- Samples/VolumeTex/include/VolumeRenderable.h
- Samples/VolumeTex/src/VolumeRenderable.cpp
> Samples: VolumeTex - update correct technique when RTSS is used

- Tests/VisualTests/Context/src/TestContext.cpp
> TestContext: enable MSAA to test alpha to coverage and MSAA resolve

- RenderSystems/GL/include/OgreGLRenderSystem.h
- RenderSystems/GL/include/OgreGLStateCacheManager.h
- RenderSystems/GL/src/OgreGLRenderSystem.cpp
- RenderSystems/GL/src/OgreGLStateCacheManager.cpp
- RenderSystems/GL3Plus/include/OgreGL3PlusRenderSystem.h
- RenderSystems/GL3Plus/include/OgreGL3PlusStateCacheManager.h
- RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusStateCacheManager.cpp
- RenderSystems/GLES2/include/EAGL/OgreEAGLES2Context.h
- RenderSystems/GLES2/include/OgreGLES2RenderSystem.h
- RenderSystems/GLES2/include/OgreGLES2StateCacheManager.h
- RenderSystems/GLES2/src/EAGL/OgreEAGL2Window.mm
- RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
- RenderSystems/GLES2/src/OgreGLES2StateCacheManager.cpp
- RenderSystems/GLSupport/CMakeLists.txt
- RenderSystems/GLSupport/include/OgreGLStateCacheManagerCommon.h
- RenderSystems/GLSupport/src/OgreGLStateCacheManagerCommon.cpp
- Tests/VisualTests/Context/src/TestContext.cpp
- Tests/VisualTests/PlayPen/src/PlayPenTests.cpp
- Tests/VisualTests/VTests/src/StencilShadowTest.cpp
> GLSupport - move more code into GLStateCacheManagerCommon

- CMake/FeatureSummary.cmake
- CMake/PrepareThreadingOptions.cmake
- CMake/Templates/OgreBuildSettings.h.in
- CMakeLists.txt
- OgreMain/include/OgreAtomicObject.h
- OgreMain/include/OgreAtomicScalar.h
- OgreMain/include/OgrePrerequisites.h
- OgreMain/include/OgreResource.h
- OgreMain/include/OgreResourceManager.h
- OgreMain/include/OgreSharedPtr.h
- OgreMain/src/OgreMaterial.cpp
- OgreMain/src/OgreResource.cpp
- OgreMain/src/OgreTexture.cpp
also enable threading via std::thread using thread_type=3
fixes #416
> Main: add OGRE_USE_STD11 option and use std::shared_ptr when set

- OgreMain/include/OgreHardwareVertexBuffer.h
- OgreMain/include/OgreSharedPtr.h
- OgreMain/include/OgreSubEntity.h
- RenderSystems/Direct3D11/include/OgreD3D11VertexDeclaration.h
- RenderSystems/Direct3D9/include/OgreD3D9VertexDeclaration.h
- RenderSystems/Direct3D9/src/OgreD3D9VertexDeclaration.cpp
- RenderSystems/GLSupport/include/OgreGLVertexArrayObject.h
- RenderSystems/GLSupport/src/OgreGLVertexArrayObject.cpp
> Main: implement SPFM_NONE with OGRE_USE_STD11

- RenderSystems/GL3Plus/include/OgreGL3PlusHardwareBuffer.h
- RenderSystems/GL3Plus/include/OgreGL3PlusHardwareBufferManager.h
- RenderSystems/GL3Plus/include/OgreGL3PlusHardwareCounterBuffer.h
- RenderSystems/GL3Plus/include/OgreGL3PlusHardwareIndexBuffer.h
- RenderSystems/GL3Plus/include/OgreGL3PlusHardwareShaderStorageBuffer.h
- RenderSystems/GL3Plus/include/OgreGL3PlusHardwareUniformBuffer.h
- RenderSystems/GL3Plus/include/OgreGL3PlusTextureBuffer.h
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareBufferManager.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareCounterBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareIndexBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareShaderStorageBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareUniformBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareVertexBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusTextureBuffer.cpp
- RenderSystems/GLES2/include/OgreGLES2HardwareBuffer.h
- RenderSystems/GLES2/include/OgreGLES2HardwareBufferManager.h
- RenderSystems/GLES2/include/OgreGLES2HardwareIndexBuffer.h
- RenderSystems/GLES2/include/OgreGLES2HardwarePixelBuffer.h
- RenderSystems/GLES2/include/OgreGLES2HardwareUniformBuffer.h
- RenderSystems/GLES2/src/OgreGLES2HardwareBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwareBufferManager.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwareIndexBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwarePixelBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwareUniformBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwareVertexBuffer.cpp
> GL3Plus: unify HardwareBuffer implementations similar to D3D11

- Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp
> Create materials into proper terrain group.

- RenderSystems/Direct3D11/include/OgreD3D11RenderWindow.h
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- RenderSystems/Direct3D11/src/OgreD3D11RenderWindow.cpp
Win10 SDK && Win10 runtime && useFlipMode = true
> [D3D11] Use DXGI_SWAP_EFFECT_FLIP_DISCARD if all stars are aligned:

- RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm
> [OSX] Fix crash when embedding OgreOSXCocoaWindow in external window

- Components/RTShaderSystem/src/OgreShaderGenerator.cpp
- Components/Terrain/include/OgreTerrainMaterialGenerator.h
- Components/Terrain/src/OgreTerrainMaterialGenerator.cpp
- Docs/src/tutorials/basictutorials/basictutorial2.md
- OgreMain/include/OgreLight.h
- OgreMain/include/OgreScriptCompiler.h
- OgreMain/src/OgreLight.cpp
- OgreMain/src/OgreScriptCompiler.cpp
- Samples/DeferredShading/include/DeferredShadingDemo.h
- Samples/MeshLod/src/MeshLod.cpp
- Samples/NewInstancing/src/NewInstancing.cpp
- Samples/PNTrianglesTessellation/include/PNTrianglesTessellation.h
- Samples/ShaderSystem/src/ShaderSystem.cpp
- Samples/Shadows/include/Shadows.h
- Samples/SkeletalAnimation/include/SkeletalAnimation.h
- Samples/Tutorials/BasicTutorial2.cpp
- Samples/VolumeTerrain/src/VolumeTerrain.cpp
- Tests/VisualTests/PlayPen/src/PlayPenTests.cpp
and deprecate the rest of the positoning API
> Main: Light - default to NEGATIVE_UNIT_Z direction

- OgreMain/include/OgreTextureUnitState.h
- OgreMain/src/OgreTextureUnitState.cpp
- Samples/Compositor/include/Compositor.h
- Samples/CubeMapping/include/CubeMapping.h
- Samples/DynTex/include/DynTex.h
- Samples/Fresnel/include/Fresnel.h
- Samples/Media/materials/scripts/Dither.material
- Samples/Media/materials/scripts/Examples-Advanced.material
- Samples/Media/materials/scripts/Examples-DynTex.material
- Samples/Media/materials/scripts/Examples.material
- Samples/Media/materials/scripts/Halftone.material
simplifies logic. Behavior now matches GpuProgramUsage
> Main: TextureUnitState - do not delay loading of Textures

- OgreMain/src/OgreTextureUnitState.cpp
- correct setBlank()
- correct TextureType in setCubicTextureName()
- catch invalid texture names and display warning texture as before
> Main: TextureUnitState - fix direct creation fallout

- OgreMain/src/OgreScriptLexer.cpp
- Samples/Media/materials/scripts/HW_VTFInstancing.material
- Samples/Media/materials/scripts/Island.material
> Add errors for missing braces in script files.

- RenderSystems/GL3Plus/CMakeLists.txt
> GL3Plus: Fix linking libdl on Unixes

- Components/Bites/CMakeLists.txt
> OgreBites: Fix linking X11 on Linux/*BSD

- CMake/Dependencies.cmake
Update freetype download website.
> Update freetype download website.

- OgreMain/include/OgreMatrix4.h
- Tests/OgreMain/src/VectorTests.cpp
We talked a bit on gitter about this, would you take this one in? (I'm proposing the same change to the v2-1 branch over at bitbucket)
> OgreMatrix4.h: add ctor that takes pointer to 16 floats

- Components/HLMS/src/OgreHlmsShaderGenerator.cpp
- OgreMain/include/OgreString.h
- OgreMain/include/OgreStringConverter.h
- OgreMain/src/OgreBillboardChain.cpp
- OgreMain/src/OgreRibbonTrail.cpp
- OgreMain/src/OgreScriptTranslator.cpp
- OgreMain/src/OgreStringConverter.cpp
- RenderSystems/GLES2/src/EAGL/OgreEAGL2Window.mm
- RenderSystems/GLSupport/src/EGL/X11/OgreX11EGLWindow.cpp
- RenderSystems/GLSupport/src/GLX/OgreGLXWindow.cpp
- RenderSystems/GLSupport/src/OSX/OgreOSXCocoaWindow.mm
- Tests/OgreMain/src/StringTests.cpp
and replace code in ScriptTranslator and HLMS
> Main: refactor StringConverter to make it more versatile

- Components/Bites/src/OgreApplicationContext.cpp
- OgreMain/include/OgreGpuProgramParams.h
- OgreMain/src/OgreGpuProgramManager.cpp
to simplify various computations
> Main: GpuProgramParams - use BaseConstantType to define GpuConstantType

- OgreMain/src/OgreScriptCompiler.cpp
- OgreMain/src/OgreScriptLexer.cpp
see https://github.com/RigsOfRods/rigs-of-rods/pull/1523
> Script: do not treat single '$' as variables and print var name on error

- RenderSystems/GL/src/OgreGLStateCacheManager.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusStateCacheManager.cpp
- RenderSystems/GLES2/src/OgreGLES2StateCacheManager.cpp
- RenderSystems/GLSupport/include/OgreGLStateCacheManagerCommon.h
> GL*: make sure StateCache is fully disabled when not explicitly enabled

- OgreMain/include/OgreVector.h
and maintain backwards compatibility
> Vector: move arithmetic ops member funcs again to ease bindings

- CMake/InstallDependencies.cmake
Install Zlib, ZZiplib and freetype for Emscripten.
> Install do install dependencies for Emscripten too.

- .travis.yml
- OgreMain/src/OgreScriptTranslator.cpp
- OgreMain/src/OgreString.cpp
- RenderSystems/GLES2/CMakeLists.txt
> ci: upgrade to xcode10

- OgreMain/include/OgreRenderTarget.h
- OgreMain/include/OgreTexture.h
which can be correctly wrapped for bindings
> Main: Texture & RenderTarget - add simplified getCustomAttribute

- CMake/Dependencies.cmake
Refer to https://github.com/OGRECave/ogre/issues/843. I commit this change and tested in Linux.
> Use system freetype library if found

- Components/MeshLodGenerator/src/OgreLodInputProviderBuffer.cpp
follow up to affebef7ed485c47565246ed1dacca89b3c61982
> MeshLod: fix Wmaybe-uninitialized warning v2

- Components/Bites/include/OgreBites.i
- OgreMain/include/Ogre.i
- OgreMain/include/OgreAnimationState.h
- OgreMain/include/OgreController.h
- OgreMain/include/OgrePredefinedControllers.h
- OgreMain/src/OgreControllerManager.cpp
- Samples/CameraTrack/include/CameraTrack.h
- Samples/Common/include/Sample.h
- Samples/DeferredShading/include/DeferredShadingDemo.h
- Samples/DeferredShading/include/SharedData.h
- Samples/DeferredShading/src/DeferredShading.cpp
- Samples/FacialAnimation/include/FacialAnimation.h
- Samples/Lighting/include/Lighting.h
- Samples/Shadows/include/Shadows.h
- Samples/SkeletalAnimation/include/SkeletalAnimation.h
- Samples/VolumeTex/src/VolumeTex.cpp
> Controllers

- Components/Bites/include/OgreInput.h
I've corrected the SDLK_PAGEDOWN value. Please have a look at it. Thanks
fixes #988
> Bites: Input - corrected the SDLK_PAGEDOWN value

- OgreMain/include/OgrePrerequisites.h
- OgreMain/include/OgreRenderSystem.h
- RenderSystems/Direct3D11/include/OgreD3D11RenderSystem.h
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- RenderSystems/Direct3D9/include/OgreD3D9RenderSystem.h
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
- RenderSystems/GL/include/OgreGLRenderSystem.h
- RenderSystems/GL/src/OgreGLRenderSystem.cpp
- RenderSystems/GL3Plus/include/GLSL/OgreGLSLShader.h
- RenderSystems/GL3Plus/include/OgreGL3PlusRenderSystem.h
- RenderSystems/GL3Plus/src/GLSL/OgreGLSLShader.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
- RenderSystems/GLES2/include/OgreGLES2RenderSystem.h
- RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
while keeping the old name alias for compatibility.
> Main: GpuProgramParametersSharedPtr -> const GpuProgramParametersPtr&

- Components/RTShaderSystem/include/OgreShaderProgram.h
- Components/RTShaderSystem/include/OgreShaderProgramManager.h
- Components/RTShaderSystem/src/OgreShaderGLSLProgramProcessor.cpp
- Components/RTShaderSystem/src/OgreShaderProgram.cpp
- Components/RTShaderSystem/src/OgreShaderProgramManager.cpp
- Samples/Media/RTShaderLib/GLSL/SampleLib_InstancedViewports.glsl
- Samples/ShaderSystem/src/OgreShaderExInstancedViewports.cpp
and propagate them correctly for attached GLSL shader libs
> RTSS: ShaderProgram - allow preprocessor defines

- OgreMain/include/OgreTexture.h
- OgreMain/src/OgreTexture.cpp
- RenderSystems/Direct3D9/include/OgreD3D9Texture.h
- RenderSystems/Direct3D9/src/OgreD3D9Texture.cpp
- Samples/Media/RTShaderLib/GLSL/SGXLib_PerPixelLighting.glsl
- Samples/Media/RTShaderLib/HLSL_Cg/SGXLib_PerPixelLighting.cg
> Main: Texture::getBuffer - return by const ref

- Components/Csharp/CMakeLists.txt
- Components/Java/CMakeLists.txt
- Components/Python/CMakeLists.txt
- OgreMain/include/OgreGpuProgramManager.h
- OgreMain/include/OgreMeshManager.h
- OgreMain/include/OgreTextureManager.h
- OgreMain/src/OgreGpuProgramManager.cpp
- OgreMain/src/OgreMesh.cpp
> SWIG: fix Windows builds

- OgreMain/src/OgreRoot.cpp
- OgreMain/src/Threading/OgreDefaultWorkQueueStandard.cpp
> Main: fix integer overflow when num threads and use a sane limit of 2

- OgreMain/CMakeLists.txt
Build error if the Zip option disabled
> Main: fix android build without Zip

- OgreMain/include/OgreMeshManager.h
- OgreMain/src/OgreMeshManager.cpp
- OgreMain/src/OgreNode.cpp
> Main: MeshManager - move ManualResourceLoader API into separate class

- OgreMain/include/OgreSubMesh.h
- OgreMain/src/OgreEntity.cpp
- OgreMain/src/OgreNode.cpp
- OgreMain/src/OgreSubMesh.cpp
- Tests/OgreMain/src/MeshSerializerTests.cpp
this simplifies code and allows correctly resolving by resource group
> Main: SubMesh - store MaterialPtr instead of material name

- RenderSystems/GL/src/GLSL/include/OgreGLSLProgram.h
- RenderSystems/GLSupport/include/GLSL/OgreGLSLShaderCommon.h
as it is the only one supporting that
> GLSupport: move getPass*States override to GL

- OgreMain/include/OgreRenderSystem.h
- OgreMain/src/OgreRenderSystem.cpp
- RenderSystems/Direct3D9/include/OgreD3D9RenderSystem.h
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
- RenderSystems/GL/include/OgreGLRenderSystem.h
- RenderSystems/GL/src/OgreGLRenderSystem.cpp
- RenderSystems/GL/src/OgreGLRenderToVertexBuffer.cpp
and generally avoid overloading the internal implementations.
> Main: RenderSystem - fix _setProjectionMatrix fallback code

- Components/RTShaderSystem/include/OgreShaderFunctionAtom.h
- Components/RTShaderSystem/src/OgreShaderFunctionAtom.cpp
- Tests/Components/RTShaderSystemTests.cpp
> RTSS: correct and simplify FunctionInvocation Operand comparison + test

- OgreMain/src/OgreParticleEmitter.cpp
> Main: ParticleEmitter - add asserts to catch invalid velocity values

- OgreMain/include/OgreEntity.h
- OgreMain/src/OgreEntity.cpp
- PlugIns/OctreeSceneManager/src/OgreOctreeSceneQuery.cpp
- PlugIns/PCZSceneManager/src/OgrePCZSceneQuery.cpp
and deprecated iterator wrapper based access to them
> Main: Entity - use vector based storage for child objects

- Components/Overlay/include/OgreFont.h
- Components/Overlay/src/OgreFont.cpp
> Add _setMaterial method to Font

- CMake/Templates/app.gradle.in
- Samples/AndroidJNI/AndroidTextureOES.java
> Samples: AndroidJNI - properly request Camera permissions

- Components/Terrain/src/OgreTerrainMaterialGenerator.cpp
- OgreMain/include/OgreManualObject.h
- OgreMain/src/OgreManualObject.cpp
This fixes #1209 and #1099 and also has a little bit of formatting cleanup.
> Add MaterialPtr overloads to ManualObject

- OgreMain/src/OgreOptimisedUtilSSE.cpp
- OgreMain/src/SSE2NEON.h
> Main: update SSE2NEON to fix softwareVertexSkinning

- OgreMain/src/OgreImage.cpp
- OgreMain/src/OgrePixelConversions.h
- Tests/OgreMain/src/PixelFormatTests.cpp
> Main: add optimized PF_R8 scaling & conversion

- Samples/Tutorials/CMakeLists.txt
- Added CXX 11 as it does not build without it
- Changed CMAKE_BINARY_DIR to CMAKE_CURRENT_BINARY_DIR to add compatibiltiy with add_subdirectory()
- Cleaned up CMakeLists.txt for better clarity
> Updated CMakeLists.txt

- RenderSystems/GLSupport/src/EGL/X11/OgreX11EGLWindow.cpp
port of 3296aedb9d582ebdc08fd27e6e5160a9f623ee06
fixes #1253
> GLSupport: EGL - correctly handle windowMovedOrResized with parent win

- CMakeLists.txt
as per https://forums.ogre3d.org/viewtopic.php?f=5&p=545942
> CMake: disable precompiled headers on MinGW

- OgreMain/src/OgrePass.cpp
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- Samples/Browser/include/SampleBrowser.h
- Samples/Common/include/SampleContext.h
- Samples/ImGui/include/ImGuiDemo.h
- Samples/Media/materials/programs/GLSL/ShowUV.glsl
- Samples/Media/particle/Examples.particle
- Samples/Terrain/include/Terrain.h
- hook up controls in ImGui sample
- fix nimbus particle renderer for RTSS
- do not try to save terrain: fails on android, wrong group anyway
> Samples: multiple small fixes

- CMake/Dependencies.cmake
> CMake: bump pugixml to 1.10 and make sure it can be linked against

- Media/RTShaderLib/GLSL/SGXLib_IntegratedPSSM.glsl
- Media/Terrain/TerrainHelpers.glsl
also complete the fix for RTSS
> Terrain: fix shadows with reversed-z & depth textures

- CMake/Dependencies.cmake
- CMakeLists.txt
- Components/Bites/CMakeLists.txt
Fixes in CMake for Xaw and Bites checks.
> Xaw bites cmake fixes

- OgreMain/src/OgreEntity.cpp
- OgreMain/src/OgreInstanceBatch.cpp
Smaller fixes for things that Valgrind complained about.
> Memory fixes

- Components/RTShaderSystem/src/OgreShaderFFPTexturing.cpp
- OgreMain/src/OgreSceneManager.cpp
observed regression in the Segmented Lights Sample
> RTSS: Texturing - switch back to inspecting srcPass

- RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp
- RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLMonolithicProgram.cpp
- RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLSeparableProgram.cpp
- RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESLinkProgram.cpp
- RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramPipeline.cpp
> GL*: fix uploading sampler array uniforms

- OgreMain/src/OgreManualObject.cpp
> Fixed wrong material name in ManualObjectSection

- PlugIns/CgProgramManager/src/OgreCgProgram.cpp
And seems VS Code also wanted to remove some trailing spaces, which I guess would be OK as well?
> Fixed CgProgramManager to compile

- Components/RTShaderSystem/include/OgreShaderExDualQuaternionSkinning.h
- Components/RTShaderSystem/src/OgreShaderExDualQuaternionSkinning.cpp
- Components/RTShaderSystem/src/OgreShaderParameter.cpp
- Docs/src/high-level-programs.md
- Media/RTShaderLib/GLSL/FFPLib_Transform.glsl
- Media/RTShaderLib/GLSL/SGXLib_DualQuaternion.glsl
- Media/RTShaderLib/HLSL_Cg/SGXLib_DualQuaternion.cg
- RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp
- RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLMonolithicProgram.cpp
- RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLSeparableProgram.cpp
- RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESLinkProgram.cpp
fixes https://github.com/OGRECave/ogre/issues/425
> Non square

- OgreMain/include/Ogre.i
Allows the use of RenderSystem.getConfigOptions()
> Added template for ConfigOptionMap

- Docs/src/high-level-programs.md
- PlugIns/CgProgramManager/src/OgreCgProgram.cpp
- RenderSystems/Direct3D11/src/OgreD3D11HLSLProgram.cpp
- RenderSystems/Direct3D9/src/OgreD3D9HLSLProgram.cpp
- RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESCgProgram.cpp
- Samples/Media/DeferredShadingMedia/deferred_post.program
- Samples/Media/materials/scripts/Examples.program
- Samples/Media/materials/scripts/Ocean.material
- Samples/Media/materials/scripts/RadialBlur.material
- Tests/Media/glow.material
and simplify scripts accordingly
> D3D11/ D3D9/ Cg: set entry point to "main" by default

- OgreMain/include/Ogre.i
- OgreMain/include/OgreCommon.h
- OgreMain/include/OgreHardwarePixelBuffer.h
- OgreMain/src/OgreHardwarePixelBuffer.cpp
- OgreMain/src/OgreTexture.cpp
- RenderSystems/Direct3D11/src/OgreD3D11HardwarePixelBuffer.cpp
- RenderSystems/GL/src/OgreGLHardwarePixelBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwarePixelBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusTextureBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwarePixelBuffer.cpp
makes code a lot more readable in many places
> Main: Box - introduce getSize & getOrigin convenience functions

- Tools/CMakeLists.txt
- Tools/MeshUpgrader/CMakeLists.txt
- Tools/Readme.txt
- Tools/VRMLConverter/CMakeLists.txt
- Tools/XMLConverter/CMakeLists.txt
- Tools/XMLConverter/src/main.cpp
also fix uninitialized values and remove remains of dropped features
fixes #1468
> Tools: XMLConverter - correctly warn about dropped flags

- OgreMain/include/OgreMath.h
- OgreMain/include/OgreMatrix3.h
- OgreMain/src/OgreCamera.cpp
- OgreMain/src/OgreSceneManager.cpp
- OgreMain/src/OgreSceneNode.cpp
- OgreMain/src/OgreShadowCameraSetup.cpp
- OgreMain/src/OgreShadowCameraSetupFocused.cpp
- OgreMain/src/OgreShadowCameraSetupPlaneOptimal.cpp
- Samples/NewInstancing/src/NewInstancing.cpp
- Samples/VolumeTex/src/ThingRenderable.cpp
- Samples/VolumeTex/src/VolumeRenderable.cpp
to do away with the various handness and sign error.
(OGRE uses right handed convention)
> Main: factor out Math::lookRotation

- OgreMain/src/Android/OgreAPKFileSystemArchive.cpp
> Android: APKFileSystemArchive - properly set stream name to filename

- OgreMain/include/OgreGpuProgramParams.h
- OgreMain/src/OgreGpuProgramParams.cpp
- Tests/OgreMain/src/General.cpp
> Main: GpuSharedParameters - properly handle param offset

- OgreMain/include/OgreGpuProgramParams.h
- OgreMain/src/OgreGpuProgramParams.cpp
- Tests/OgreMain/src/General.cpp
> GpuSharedParameters - Fixed for offset calculation

- Samples/LightShafts/include/LightShafts.h
- Samples/Media/materials/programs/HLSL_Cg/LightShafts.hlsl
- Samples/Media/materials/scripts/LigthShafts.material
also generally simplify material
> Samples: LightShafts - use standard depth texture & spotlight params

- PlugIns/DotScene/src/DotSceneLoader.cpp
also report what went wrong on error
> DotSceneLoader - fix compilation w/o Terrain, fix crash on parse error

- Samples/Browser/CMakeLists.txt
> Samples: OSX - correctly set rpath for browser

- OgreMain/include/OgreRenderSystem.h
- OgreMain/src/OgreRenderSystem.cpp
- RenderSystems/Direct3D11/include/OgreD3D11RenderSystem.h
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- RenderSystems/Direct3D9/include/OgreD3D9RenderSystem.h
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
- RenderSystems/GLSupport/include/OgreGLRenderSystemCommon.h
consequently make it non-virtual
> Main: unify RenderSystem::reinitialise

- OgreMain/src/OgreTexture.cpp
> Main: Texture - allow different PixelFormat for different cubemap faces

- OgreMain/include/OgreVector.h
This seems to fix the issue. I'm not sure why though, any thoughts?
fixes #1502
> Fixes compilation error C2338 when building with double precision

- RenderSystems/GLSupport/src/GLSL/OgreGLSLPreprocessor.cpp
- Tests/RenderSystems/GLSupport/GLSLTests.cpp
GLSL Code before preprocessing:
```
#define RIGHT(left,right) (right)
#define LEFT(left,right) (left)
#define USE(a,b,F) F(a,b)
USE(A,B,LEFT)
USE(RIGHT(A,C),B,LEFT)
USE(A,B,RIGHT(left,LEFT))
```
Current output:
```
()(A, B)
()((C), B)
(())(A, B)
```
Fixed and correct output:
```
(A)
((C))
(LEFT)(A,B)
```
Added some tests.
Everything (concerning this) was checked against the output from `gcc -E [file]` (on gcc (Arch Linux 9.3.0-1) 9.3.0).
Questions, suggestions and/or comments?
(I am calling this a “feature”, but I am also surprised that I have not found any issue relating to this here at all…)
> added macro recursion feature to GLSLPreprocessor

- OgreMain/include/OgrePlatform.h
patch by Manuel A. Fernandez Montecelo in Debian
> add riscv64 as 64bit architecture

- OgreMain/include/OgreZip.h
- OgreMain/src/Android/OgreAPKZipArchive.cpp
- OgreMain/src/OgreZip.cpp
> Main: EmbeddedZipArchiveFactory - prevent leaking Archives

- CMake/Dependencies.cmake
- Components/Bites/include/OgreApplicationContextQt.h
- Components/Bites/src/OgreApplicationContextQt.cpp
- appveyor.yml
- ci-build.cmake
fixes #1550
fixes https://github.com/OGRECave/ogitor/issues/31
> CI: enable Qt in SDK build

- CMake/Dependencies.cmake
> Use the right variable to determine if Qt was found

- CMake/Dependencies.cmake
- Components/Csharp/CMakeLists.txt
- Components/Java/CMakeLists.txt
- Components/Python/CMakeLists.txt
> CMake: clean-up swig lookup & add quiet flag for optional dependencies

- OgreMain/src/OgreHardwareVertexBuffer.cpp
- OgreMain/src/OgreVertexIndexData.cpp
- Tools/MeshUpgrader/src/main.cpp
- Tools/XMLConverter/src/OgreXMLMeshSerializer.cpp
- Tools/XMLConverter/src/main.cpp
> Tools: XMLConverter & MeshUpgrader add -byte option to use ubyte4_norm

- OgreMain/include/OgrePose.h
see https://github.com/OGRECave/meshmagick/pull/2
> Main: Pose - add mutable vertex access for offline tools

- OgreMain/include/OgreHardwareBuffer.h
- OgreMain/src/OgreHardwarePixelBuffer.cpp
the cost of this is neglectable to the driver overhead
> Main: HardwareBuffer - guard lock usage with runtime asserts

- Docs/src/tutorials/numpy.md
- OgreMain/include/Ogre.i
- Samples/Python/bites_sample.py
- Samples/Python/numpy_sample.py
- Samples/Python/sample.py
including numpy arrays and range()
> Python: allow using sequences instead of Vector and ColourValaue

- .gitmodules
- CMakeLists.txt
- Components/Overlay/CMakeLists.txt
- Components/Python/CMakeLists.txt
people (and github releases) do not cope with submodules well
fixes #1332
> Overlay: use cmake to download imgui instead of git submodule

- OgreMain/src/OgreHighLevelGpuProgram.cpp
- Tests/OgreMain/src/General.cpp
also fix crash when there is no newline after #include. Add Test to
verify.
> Main: HighLevelGpuProgram - correctly resolve #include in #include

- OgreMain/include/OgreSceneLoaderManager.h
- OgreMain/src/OgreCodec.cpp
- OgreMain/src/OgreSceneLoaderManager.cpp
- PlugIns/BSPSceneManager/include/OgreBspLevel.h
- PlugIns/BSPSceneManager/include/OgreBspSceneLoader.h
- PlugIns/BSPSceneManager/include/OgreBspSceneManagerPlugin.h
- PlugIns/BSPSceneManager/include/OgreQuake3Level.h
- PlugIns/BSPSceneManager/src/OgreBspLevel.cpp
- PlugIns/BSPSceneManager/src/OgreBspSceneLoader.cpp
- PlugIns/BSPSceneManager/src/OgreBspSceneManager.cpp
- PlugIns/BSPSceneManager/src/OgreBspSceneManagerPlugin.cpp
- PlugIns/BSPSceneManager/src/OgreQuake3Level.cpp
- PlugIns/DotScene/include/OgreDotSceneLoader.h
- PlugIns/DotScene/src/DotSceneLoader.cpp
also some const correctness for BSPSceneManager
> Main: deprecate SceneLoaderManager API in favor of new Codec API

- Components/Csharp/CMakeLists.txt
- Components/Java/CMakeLists.txt
> SWIG: enable imgui with C# and Java as well

- OgreMain/src/OgreParticleSystem.cpp
and replace iterators by range based for as applicable
> Main: ParticleSystem - set owner on creation instead of status change

- Media/ShadowVolume/OgreUnifiedShader.h
> Main: UnifiedShader - add texture1D alias for HLSL

- OgreMain/include/OgreParticle.h
- OgreMain/include/OgreParticleEmitter.h
- OgreMain/src/OgreParticleSystem.cpp
to avoid syncing emitted emitters
> Main: ParticleEmitter - use inherited Particle pos

- OgreMain/include/OgreBillboard.h
- OgreMain/include/OgreBillboardParticleRenderer.h
- OgreMain/include/OgreBillboardSet.h
- OgreMain/include/OgreParticle.h
- OgreMain/include/OgreParticleSystem.h
- OgreMain/include/OgreParticleSystemRenderer.h
- OgreMain/src/OgreBillboard.cpp
- OgreMain/src/OgreBillboardSet.cpp
- OgreMain/src/OgreParticle.cpp
- OgreMain/src/OgreParticleSystem.cpp
the existing flags actually did not save us any branching.
Also update corresponding Particle classes.
> Main: BillboardSet - simplify per Billboard property handling

- Components/Overlay/src/OgreImGuiOverlay.cpp
- OgreMain/include/Ogre.i
- OgreMain/include/OgreHardwareBuffer.h
- OgreMain/include/OgreHardwareBufferManager.h
- OgreMain/include/OgreTexture.h
- OgreMain/include/OgreTextureManager.h
- OgreMain/src/OgreMesh.cpp
- OgreMain/src/OgreVertexIndexData.cpp
- RenderSystems/Direct3D11/src/OgreD3D11Mappings.cpp
- RenderSystems/Direct3D9/src/OgreD3D9HardwareBufferManager.cpp
- RenderSystems/Direct3D9/src/OgreD3D9HardwareIndexBuffer.cpp
- RenderSystems/Direct3D9/src/OgreD3D9HardwareVertexBuffer.cpp
- RenderSystems/Direct3D9/src/OgreD3D9Mappings.cpp
- RenderSystems/GL/src/OgreGLHardwareBufferManager.cpp
- RenderSystems/GL/src/OgreGLHardwareIndexBuffer.cpp
- RenderSystems/GL/src/OgreGLHardwarePixelBuffer.cpp
- RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwarePixelBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusTextureBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwareBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwarePixelBuffer.cpp
- RenderSystems/GLSupport/src/OgreGLHardwarePixelBufferCommon.cpp
- RenderSystems/Metal/src/OgreMetalHardwareBufferCommon.mm
- add human readable aliases for common modes
- make clear which are actual modes and which are merely detail bits
> Main: clean-up/ refactor HBU flags

- OgreMain/include/OgreHardwareBuffer.h
- OgreMain/include/OgreTexture.h
- OgreMain/src/OgreVertexIndexData.cpp
- RenderSystems/Direct3D11/include/OgreD3D11HardwareBuffer.h
- RenderSystems/Direct3D11/include/OgreD3D11HardwareIndexBuffer.h
- RenderSystems/Direct3D11/include/OgreD3D11HardwareVertexBuffer.h
- RenderSystems/Direct3D11/src/OgreD3D11HardwareBuffer.cpp
- RenderSystems/Direct3D11/src/OgreD3D11HardwareBufferManager.cpp
- RenderSystems/Direct3D11/src/OgreD3D11HardwareIndexBuffer.cpp
- RenderSystems/Direct3D11/src/OgreD3D11HardwareUniformBuffer.cpp
- RenderSystems/Direct3D11/src/OgreD3D11HardwareVertexBuffer.cpp
- RenderSystems/Direct3D9/include/OgreD3D9HardwareIndexBuffer.h
- RenderSystems/Direct3D9/include/OgreD3D9HardwareVertexBuffer.h
- RenderSystems/Direct3D9/include/OgreD3D9Prerequisites.h
- RenderSystems/Direct3D9/src/OgreD3D9HardwareBufferManager.cpp
- RenderSystems/Direct3D9/src/OgreD3D9HardwareIndexBuffer.cpp
- RenderSystems/Direct3D9/src/OgreD3D9HardwareVertexBuffer.cpp
- RenderSystems/Direct3D9/src/OgreD3D9Mappings.cpp
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
- RenderSystems/GL/src/OgreGLHardwareBufferManager.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusHardwareBuffer.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusTextureBuffer.cpp
- RenderSystems/GLES2/src/OgreGLES2HardwareBuffer.cpp
- RenderSystems/Metal/src/OgreMetalHardwareBufferCommon.mm
> D3D11: properly use HBU setting instead of abusing systemMemory flag

- RenderSystems/Direct3D11/include/OgreD3D11HardwareBuffer.h
- RenderSystems/Direct3D11/include/OgreD3D11HardwarePixelBuffer.h
- RenderSystems/Direct3D11/src/OgreD3D11HardwareBuffer.cpp
- RenderSystems/Direct3D11/src/OgreD3D11HardwarePixelBuffer.cpp
as we never use both at the same time
> D3D11: re-use shadow buffer for temporary staging

- OgreMain/src/OgreShadowRenderer.cpp
when replacing the Sampler
see #1698
> Main: ShadowRenderer - fix FT_MIP setting being overwritten

- OgreMain/include/Ogre.i
- OgreMain/include/OgreCamera.h
- OgreMain/include/OgreDefaultDebugDrawer.h
- OgreMain/include/OgreFrustum.h
- OgreMain/include/OgreNode.h
- OgreMain/include/OgrePrerequisites.h
- OgreMain/include/OgreSceneManager.h
- OgreMain/include/OgreSceneNode.h
- OgreMain/src/OgreCamera.cpp
- OgreMain/src/OgreDefaultDebugDrawer.cpp
- OgreMain/src/OgreEntity.cpp
- OgreMain/src/OgreFrustum.cpp
- OgreMain/src/OgreManualObject.cpp
- OgreMain/src/OgreSceneManager.cpp
- OgreMain/src/OgreSceneNode.cpp
- PlugIns/OctreeSceneManager/src/OgreOctreeSceneManager.cpp
- PlugIns/OctreeZone/src/OgreOctreeZone.cpp
- PlugIns/PCZSceneManager/src/OgreDefaultZone.cpp
and allow overriding using the abstract DebugDrawer interface
> Main: unify debug drawing in the DefaultDebugDrawer class

- Components/Bites/src/OgreGLXConfigDialog.cpp
- OgreMain/src/OgrePixelFormat.cpp
and fix usage in GLXConfigurator
fixes  #1713
> Main: PixelUtil - bulkPixelConversion use production assert

- OgreMain/include/OgreEntity.h
- OgreMain/include/OgreHardwareVertexBuffer.h
- OgreMain/include/OgreMaterialManager.h
- OgreMain/include/OgreRoot.h
- OgreMain/src/OgreEntity.cpp
- OgreMain/src/OgreHardwareVertexBuffer.cpp
- OgreMain/src/OgreMaterialManager.cpp
- OgreMain/src/OgreRoot.cpp
> Main: VertexBufferBinding - inline hasInstanceData

- OgreMain/include/OgreHardwareVertexBuffer.h
as that assignment actually depends on the used material
> Main: VES  - alias DIFFUSE/ SPECULAR to COLOUR1/2

- Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp
- Components/Terrain/src/OgreTerrainMaterialShaderHelperGLSL.cpp
to make code more self-contained
reverts 787171e03c901da33cd416f9ee075f014cb1e8dd
> Terrain: move uv multiplication into vertex fragment

- PlugIns/Assimp/src/AssimpLoader.cpp
- default value of scale should be 1
- use correct index
fixes #1780
> AssimpCodec: fixes for getScale function

- Components/Terrain/include/OgreTerrainQuadTreeNode.h
- Components/Terrain/src/OgreTerrainQuadTreeNode.cpp
> Terrain: QuadTreeNode - use pricate inheritance instead of aggregation

- Docs/src/tutorials/basictutorials/basictutorial1.md
- Docs/src/tutorials/basictutorials/basictutorial2.md
- Docs/src/tutorials/basictutorials/basictutorial3.md
> Docs: slightly overhaul basictutorials

- OgreMain/include/OgreCamera.h
- OgreMain/include/OgreDistanceLodStrategy.h
- OgreMain/include/OgreRenderQueueSortingGrouping.h
- OgreMain/include/OgreRenderable.h
- OgreMain/src/OgreCamera.cpp
- OgreMain/src/OgreDistanceLodStrategy.cpp
- OgreMain/src/OgreMovableObject.cpp
- OgreMain/src/OgreNode.cpp
- OgreMain/src/OgreRenderQueueSortingGrouping.cpp
- OgreMain/src/OgreSubEntity.cpp
- Samples/VolumeTex/include/ThingRenderable.h
- Samples/VolumeTex/include/VolumeRenderable.h
> Main: Camera - allow to sort by depth and not by distance

- OgreMain/src/OgreCompositorInstance.cpp
bug introduced by 334fc4b75ebc0546e21e9e8ae2ece75a325bb358
> Main: Compositor - allow referencing global textures again

- Docs/src/material-scripts.md
Some format corrections in "iteration" section
> Format corrections

- Components/RTShaderSystem/src/OgreShaderFFPTexturing.cpp
- Components/RTShaderSystem/src/OgreShaderGenerator.cpp
- Docs/src/scripts.md
- OgreMain/include/OgreCompositionPass.h
- OgreMain/include/OgreCompositionTargetPass.h
- OgreMain/include/OgreCompositionTechnique.h
- OgreMain/include/OgreCompositor.h
- OgreMain/include/OgreCompositorInstance.h
- OgreMain/include/OgreCompositorManager.h
- OgreMain/include/OgreScriptCompiler.h
- OgreMain/src/OgreCompositionPass.cpp
- OgreMain/src/OgreCompositionTargetPass.cpp
- OgreMain/src/OgreCompositionTechnique.cpp
- OgreMain/src/OgreCompositor.cpp
- OgreMain/src/OgreCompositorChain.cpp
- OgreMain/src/OgreCompositorInstance.cpp
- OgreMain/src/OgreCompositorManager.cpp
- OgreMain/src/OgreSceneManager.cpp
- OgreMain/src/OgreScriptCompiler.cpp
- OgreMain/src/OgreScriptTranslator.cpp
- Samples/Media/materials/scripts/Examples-Advanced.material
- Samples/Media/materials/scripts/Examples.compositor
- Samples/Media/materials/scripts/Examples.material
- Samples/Simple/include/CubeMapping.h
- Samples/Simple/include/Fresnel.h
> Support cubemaps in Compositor scripts

- OgreMain/include/Ogre.i
> SWIG: Csharp - forward operator overloads on Vector for convenience

- OgreMain/include/Ogre.i
SplitPointList was missing so I templated it
> fixed missing SplitPointList

- Components/Overlay/include/OgreOverlayElement.h
fixes: https://github.com/OGRECave/ogre/issues/1930
> Doc: correct documentation of OgreOverlayElement

- Tools/MeshUpgrader/src/main.cpp
- Some input prompts lacked a whitespace and the input options
- Some parts of the code used the name OgreMeshUpgrade, lacking the r
> Fix some input prompts and OgreMeshUpgrade(r)

- Tools/MeshUpgrader/src/main.cpp
- Added option to set log file path
- Some outputs were not being logged (fixed)
> OgreMeshUpgrader: set log file path

- Components/Bites/src/OgreApplicationContextAndroid.cpp
> Bites: Android - fix crash on surface recreation

- Components/Csharp/CMakeLists.txt
- Components/Java/CMakeLists.txt
- Components/Python/CMakeLists.txt
- Components/Terrain/include/OgreTerrain.i
- Components/Terrain/include/OgreTerrainGroup.h
- Samples/EndlessWorld/include/EndlessWorld.h
- Samples/Simple/include/Terrain.h
> Draft terrain

- OgreMain/include/OgreException.h
- OgreMain/src/OgreException.cpp
- RenderSystems/Direct3D11/include/OgreD3D11Prerequisites.h
hence directly resolve fullDesc
> Main: Exception - avoid referencing dangling strings

- Components/Overlay/include/OgreFontManager.h
- Components/Overlay/src/OgreFontManager.cpp
- OgreMain/include/OgreCompositorManager.h
- OgreMain/include/OgreGpuProgramManager.h
- OgreMain/include/OgreHighLevelGpuProgramManager.h
- OgreMain/include/OgreMaterialManager.h
- OgreMain/include/OgreMeshManager.h
- OgreMain/include/OgreResourceManager.h
- OgreMain/include/OgreSkeletonManager.h
- OgreMain/include/OgreTextureManager.h
- OgreMain/src/OgreCompositorManager.cpp
- OgreMain/src/OgreGpuProgramManager.cpp
- OgreMain/src/OgreHighLevelGpuProgramManager.cpp
- OgreMain/src/OgreMaterialManager.cpp
- OgreMain/src/OgreMeshManager.cpp
- OgreMain/src/OgreResourceManager.cpp
- OgreMain/src/OgreSkeletonManager.cpp
- OgreMain/src/OgreTextureManager.cpp
> Main: ResourceManager - const correctness

- Components/Overlay/src/OgreFont.cpp
> Overlay: Font - remove stray debug image save

- OgreMain/include/OgreMaterialSerializer.h
- OgreMain/include/OgrePass.h
- OgreMain/src/OgreBuiltinScriptTranslators.h
- OgreMain/src/OgreMaterialSerializer.cpp
- OgreMain/src/OgrePass.cpp
- OgreMain/src/OgreScriptTranslator.cpp
- OgreMain/src/OgreShadowRenderer.cpp
but add fallback code for material scripts
fixes #1426
> Main: Pass - drop shadow_*_program_ref API

- Components/Terrain/src/OgreTerrainQuadTreeNode.cpp
- OgreMain/include/OgreCommon.h
Avoid an assertion error in runtime.
> Terrain node opt out early

- OgreMain/src/OgreSkeleton.cpp
- Tests/OgreMain/src/General.cpp
> Main: Skeleton - fix addLinkedSkeletonAnimationSource

- RenderSystems/Direct3D9/include/OgreD3D9GpuProgramManager.h
- RenderSystems/Direct3D9/src/OgreD3D9GpuProgramManager.cpp
- RenderSystems/Direct3D9/src/OgreD3D9HLSLProgram.cpp
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
> D3D9: properly register assembly language support

- RenderSystems/GLSupport/src/EGL/OgreEGLSupport.cpp
> GLSupport: fix compilation with Android NDK 20+

- Components/Bites/src/OgreTrays.cpp
> Bites: Trays - ensure glyph info is loaded

- Components/Terrain/src/OgreTerrainMaterialGenerator.cpp
- RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLSeparableProgram.cpp
Fix small memory leak and add a small optimization to map iteration.
> Terrain fix memory leak

- OgreMain/src/OgreInstanceBatchHW.cpp
> Instances: Make sure cloned vertex data is deleted.

- OgreMain/include/OgreTextureManager.h
> Main: TextureManager - add removeAllNamedSamplers

- Media/Main/GLSL_GL3Support.glsl
- Media/Main/HLSL_SM4Support.hlsl
- Media/Main/OgreUnifiedShader.h
> Mark public shader functions with @public-api

- OgreMain/include/OgreRenderWindow.h
- RenderSystems/Direct3D11/include/OgreD3D11RenderWindow.h
- RenderSystems/GLES2/include/EAGL/OgreEAGL2Window.h
- RenderSystems/GLES2/src/EAGL/OgreEAGL2Window.mm
- RenderSystems/GLSupport/include/EGL/OgreEGLWindow.h
- RenderSystems/Tiny/include/OgreTinyWindow.h
> Main: RenderWindow - setFullscreen & reposition are optional

- OgreMain/include/OgreParticleEmitter.h
- OgreMain/src/OgreParticleEmitter.cpp
> Main: ParticleEmitter - add burst method

- OgreMain/src/OgreCompositionPass.cpp
- OgreMain/src/OgreGpuProgramParams.cpp
- OgreMain/src/OgrePass.cpp
- OgreMain/src/OgreViewport.cpp
Looks like there are mismatch between Real and float, in header and source files. These changes are based on the definition in the header files.
> Fix compiling errors due to "Out of line definitions".

- Components/RTShaderSystem/include/OgreShaderParameter.h
- Components/RTShaderSystem/src/OgreShaderCGProgramWriter.cpp
- Components/RTShaderSystem/src/OgreShaderExPerPixelLighting.cpp
- Components/RTShaderSystem/src/OgreShaderExPerPixelLighting.h
- Components/RTShaderSystem/src/OgreShaderFFPLighting.cpp
- Components/RTShaderSystem/src/OgreShaderFFPLighting.h
- Components/RTShaderSystem/src/OgreShaderFunction.cpp
- Components/RTShaderSystem/src/OgreShaderGLSLProgramWriter.cpp
- Components/RTShaderSystem/src/OgreShaderProgramManager.cpp
- Docs/src/rtss.md
- Media/RTShaderLib/GLSL/SGXLib_PerPixelLighting.glsl
- Tests/Media/tests.material
- Tests/VisualTests/PlayPen/include/PlayPenTests.h
- Tests/VisualTests/PlayPen/src/PlayPenTestPlugin.cpp
- Tests/VisualTests/PlayPen/src/PlayPenTests.cpp
> RTSS: implement two-sided lighting

- OgreMain/src/OgreParticleSystem.cpp
to appease MSVC in debug mode
fixes #2185
> Main: ParticleSystem::_expire - use idiomatic remove-erase

- Docs/CMakeLists.txt
This is trivial changes allows to control docs path.
> Allow to configure docs path

- Components/RTShaderSystem/src/OgreShaderExIntegratedPSSM3.cpp
- Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp
- Media/RTShaderLib/GLSL/SGXLib_IntegratedPSSM.glsl
> RTSS: PSSM - properly respect shadow far distance

- RenderSystems/GLSupport/include/OgreGLNativeSupport.h
- RenderSystems/Metal/include/OgreMetalRenderSystem.h
- RenderSystems/Vulkan/include/OgreVulkanRenderSystem.h
- RenderSystems/Vulkan/src/OgreVulkanRenderSystem.cpp
> Docs: add Metal and Vulkan to modules and remove GLSupport

- Components/RTShaderSystem/src/OgreShaderExIntegratedPSSM3.cpp
- RenderSystems/Direct3D9/include/OgreD3D9HardwarePixelBuffer.h
- RenderSystems/Direct3D9/include/OgreD3D9MultiRenderTarget.h
- RenderSystems/Direct3D9/include/OgreD3D9Texture.h
- RenderSystems/Direct3D9/src/OgreD3D9HardwarePixelBuffer.cpp
- RenderSystems/Direct3D9/src/OgreD3D9Mappings.cpp
- RenderSystems/Direct3D9/src/OgreD3D9MultiRenderTarget.cpp
- RenderSystems/Direct3D9/src/OgreD3D9Texture.cpp
- Samples/Media/materials/scripts/DOF.material
creation works, rendering fails. Likely due to missing color buffer.
> D3D9 - depth texture support

- RenderSystems/GLSupport/include/EGL/OgreEGLSupport.h
- RenderSystems/GLSupport/src/EGL/OgreEGLSupport.cpp
- RenderSystems/GLSupport/src/EGL/OgreEGLWindow.cpp
- RenderSystems/GLSupport/src/EGL/X11/OgreX11EGLWindow.cpp
and move getDisplayName to X11 Window
> GLSupport: fix potential crash in EGLDisplay exception path

- BuildingOgre.md
Add instructions for Fedora dependencies
> Fedora setup

- CMake/Dependencies.cmake
- RenderSystems/GL3Plus/src/GLSL/src/OgreGLSLShader.cpp
- RenderSystems/GLSupport/CMakeLists.txt
> CMake: fix OpenGL build on OSX

- CMakeLists.txt
- PlugIns/GLSLang/CMakeLists.txt
- RenderSystems/GL/CMakeLists.txt
- RenderSystems/Vulkan/CMakeLists.txt
- ci-build.cmake
> add -Wl,--no-undefined and fix fallout

- PlugIns/Assimp/CMakeLists.txt
- PlugIns/Assimp/include/OgreAssimpLoader.h
- PlugIns/Assimp/src/AssimpLoader.cpp
- Tools/AssimpConverter/main.cpp
let the offline importer will provide additional quality flags
> AssimpLoader: optimize for fast loading by default

- OgreMain/src/OgreTexture.cpp
> Texture: call ManualResourceLoader as per Resource protocol

- OgreMain/src/OgreParticleSystemManager.cpp
- OgreMain/src/OgreScriptTranslator.cpp
not having the respective plugin should not be fatal
> Main: ScriptTranslator - catch missing Particle Affectors/ Emitters

- Components/Overlay/include/OgreFontManager.h
- Components/Overlay/src/OgreFontManager.cpp
- OgreMain/include/OgreCompositorManager.h
- OgreMain/include/OgreMaterialManager.h
- OgreMain/include/OgreResourceManager.h
- OgreMain/include/OgreScriptLoader.h
- OgreMain/src/OgreCompositorManager.cpp
- OgreMain/src/OgreMaterialManager.cpp
- OgreMain/src/OgreResourceManager.cpp
and unify docs at ScriptLoader interface
> Main: ResourceManager - provide common parseScript implementation

- OgreMain/include/OgrePlatform.h
> Main: clean-up OGRE_ARCH_TYPE detection

- Components/RTShaderSystem/include/OgreShaderFFPTexturing.h
- Components/RTShaderSystem/src/OgreShaderCookTorranceLighting.cpp
- Components/RTShaderSystem/src/OgreShaderCookTorranceLighting.h
- Components/RTShaderSystem/src/OgreShaderFFPTexturing.cpp
- Components/RTShaderSystem/src/OgreShaderGenerator.cpp
- Components/RTShaderSystem/src/OgreShaderPrecompiledHeaders.h
- Docs/src/rtss.md
- Media/RTShaderLib/GLSL/SGXLib_CookTorrance.glsl
- Samples/Media/materials/scripts/DamagedHelmet.material
- Samples/Simple/include/PBR.h
- based on filament equations
- also modify texturing stage to allow emissive
> RTSS: implement metallic-roughness PBR

- Components/RTShaderSystem/src/OgreShaderCookTorranceLighting.cpp
- Docs/src/rtss.md
- PlugIns/Assimp/src/AssimpLoader.cpp
- Samples/Media/materials/scripts/DamagedHelmet.material
- Samples/Media/materials/scripts/Examples.material
- Tests/VisualTests/PlayPen/include/PlayPenTests.h
- Tests/VisualTests/PlayPen/src/PlayPenTestPlugin.cpp
- Tests/VisualTests/PlayPen/src/PlayPenTests.cpp
> RTSS: CookTorrance - allow material level parametrisation

- OgreMain/src/OgreResourceGroupManager.cpp
> Main: ResourceGroupManager - unload Archive on removeResourceLocation

- CMake/Templates/project.gradle
> Android: fix build with gradle 7

- .codedocs
- Docs/CMakeLists.txt
- Docs/src/ogre-shadows.md
- Changed name to lowercase
- Add some info on how to debug the Shadow Map
- Add some info on how to init the Shadow Cameras
- Explain the differente types of Shadow Cameras
> Add some info to Shadow Mapping doc

- OgreMain/src/OgreSkyRenderer.cpp
not really performance-critical, but shortens the code
> Main: SkyBox - construct box using a triangle strip

- Components/Csharp/CMakeLists.txt
> Csharp: check for compiler presence on Linux

- Components/Bites/src/OgreAdvancedRenderControls.cpp
- Components/RTShaderSystem/include/OgreShaderGenerator.h
- Components/RTShaderSystem/src/OgreShaderGenerator.cpp
- Components/RTShaderSystem/src/OgreShaderScriptTranslator.cpp
- Docs/src/rtss.md
- OgreMain/include/OgreMaterialManager.h
- OgreMain/src/OgreMaterialManager.cpp
- OgreMain/src/OgreMaterialSerializer.cpp
- OgreMain/src/OgreRenderSystem.cpp
- PlugIns/Assimp/src/AssimpLoader.cpp
- Samples/Common/include/Sample.h
- Samples/DeferredShading/src/DeferredShading.cpp
- Samples/DeferredShading/src/GBufferSchemeHandler.cpp
- Samples/Python/raw_sample.py
- Samples/ShaderSystem/src/ShaderSystem.cpp
- Samples/ShaderSystemMultiLight/include/ShaderSystemMultiLight.h
- Samples/ShaderSystemTexturedFog/include/ShaderSystemTexturedFog.h
- Samples/Simple/include/BezierPatch.h
- Samples/Simple/include/Dot3Bump.h
- Samples/Simple/include/DualQuaternion.h
- Samples/Simple/include/Grass.h
- Samples/Simple/include/LightShafts.h
- Samples/Simple/include/SkeletalAnimation.h
- Samples/Simple/include/Terrain.h
- Samples/Simple/include/Transparency.h
- Samples/Simple/include/VolumeCSG.h
- Samples/Simple/src/NewInstancing.cpp
- Samples/Simple/src/VolumeCSG.cpp
- Samples/Simple/src/VolumeTerrain.cpp
- Tests/VisualTests/PlayPen/src/PlayPenTests.cpp
also move MSN_SHADERGEN definition to OgreMain
> Main: add top-level aliases for material schemes e.g. MSN_DEFAULT

- OgreMain/src/OgreTangentSpaceCalc.cpp
> Main: TangentSpaceCalc - dont discard existing vertex data

- Components/RTShaderSystem/include/OgreShaderExIntegratedPSSM3.h
- Components/RTShaderSystem/src/OgreShaderCookTorranceLighting.cpp
- Components/RTShaderSystem/src/OgreShaderExIntegratedPSSM3.cpp
- Components/RTShaderSystem/src/OgreShaderExPerPixelLighting.cpp
- Components/RTShaderSystem/src/OgreShaderFFPLighting.cpp
- Media/RTShaderLib/GLSL/SGXLib_CookTorrance.glsl
as shadows attenuate specific lights.
Also correctly applies surface color with CookTorrance lighting
> RTSS: PSSM - move ApplyShadowFactor to lighting stages as it should be

- PlugIns/PCZSceneManager/include/OgrePCZSceneManager.h
- PlugIns/PCZSceneManager/src/OgrePCZSceneManager.cpp
> PCZSceneManager: fix named node registration in createSceneNode override

- CMakeLists.txt
> CMake: let CMake autodetect OSX_SYSROOT

- Components/Bullet/CMakeLists.txt
> Bullet: install header files too

- Docs/License.md
Just a small change in Docs/License.md.
> update list of components using pugixml in Docs/license.md

- OgreMain/src/OgreStaticGeometry.cpp
> Main: StaticGeometry - logError if Root SceneNode is transformed

- OgreMain/src/OgreRibbonTrail.cpp
> Main: RibbonTrail - validate TrailLength

- Docs/src/high-level-programs.md
- OgreMain/src/OgreSceneManager.cpp
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- RenderSystems/Direct3D9/include/OgreD3D9RenderSystem.h
- RenderSystems/Direct3D9/include/OgreD3D9VertexDeclaration.h
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
- RenderSystems/Direct3D9/src/OgreD3D9VertexDeclaration.cpp
- RenderSystems/GL/src/OgreGLRenderSystem.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
- RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
- RenderSystems/GLSupport/include/OgreGLRenderSystemCommon.h
- RenderSystems/GLSupport/src/OgreGLRenderSystemCommon.cpp
- Samples/ShaderSystem/src/OgreShaderExInstancedViewports.cpp
using portable code
updates #2292
> Main: inject GlobalInstancingDeclaration in SceneManager instead of RS

- CMakeLists.txt
- OgreMain/src/OgreAnimation.cpp
- OgreMain/src/OgreAnimationState.cpp
Just some more refactoring loops and minor changes
> Refactoring

- OgreMain/src/OgreZip.cpp
- Tests/OgreMain/src/FileSystemArchiveTests.cpp
- Tests/OgreMain/src/ZipArchiveTests.cpp
> Main: Zip - correctly forward filename to opened datastream

- Components/Terrain/include/OgreTerrainMaterialGenerator.h
- Components/Terrain/src/OgreTerrain.cpp
- Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp
and some profile related functions
> Terrain: MaterialGenerator - deprecate layerDecl.elements

- OgreMain/include/OgreGpuProgramParams.h
nobody is using RenderMonkey any more
> Docs: improve AutoConstantType documentation/ formatting

- OgreMain/src/OgreEntity.cpp
broken in 5362b48529321f87b905d230433148df8e667257
> Main: fixup Entity::clone

- Components/Terrain/src/OgreTerrainQuadTreeNode.cpp
introduced in 93d7eb5282d31b956f008a53e837bbb820b34454
> Terrain: correctly forward visibility and query flags

- RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgramManager.cpp
This fixes an assert() being hit on opensource Linux AMD drivers when some of the uniform array elements were optimized away by the shader compiler.
> Relax an assert() not to cover legitimate cases

- Components/Terrain/src/OgreTerrain.cpp
- OgreMain/include/OgreSceneManager.h
- OgreMain/src/OgreShadowRenderer.cpp
- RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
- Samples/Simple/src/NewInstancing.cpp
> Main: ShadowRenderer - fix shadow culling frustum getting stuck

- OgreMain/src/OgreNumerics.cpp
- OgreMain/src/OgreParticleSystem.cpp
- OgreMain/src/OgreParticleSystemManager.cpp
- OgreMain/src/OgrePass.cpp
> range loop refactoring

- Components/Terrain/include/OgreTerrainMaterialGeneratorA.h
- Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp
- Samples/Simple/include/Terrain.h
it is determined by PixelFormat now
> Terrain: deprecate ReceiveDynamicShadowsDepth

- Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp
- Components/Terrain/src/OgreTerrainRTShaderSRS.cpp
- Components/Terrain/src/OgreTerrainRTShaderSRS.h
and be more clever with auto-disabling it
> Terrain: MaterialGeneratorA - respect LayerNormalMappingEnabled setting

- Components/Terrain/src/OgreTerrainRTShaderSRS.cpp
- OgreMain/src/OgreBillboardChain.cpp
- OgreMain/src/OgreCommon.cpp
- OgreMain/src/OgreManualObject.cpp
- OgreMain/src/OgreMeshSerializerImpl.cpp
- OgreMain/src/OgreParticleSystem.cpp
- OgreMain/src/OgreRenderSystem.cpp
- OgreMain/src/OgreStableHeaders.h
- OgreMain/src/OgreSubEntity.cpp
- RenderSystems/GL/src/OgreGLRenderSystem.cpp
- RenderSystems/GL/src/OgreGLStateCacheManager.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusStateCacheManager.cpp
- RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
- RenderSystems/GLES2/src/OgreGLES2StateCacheManager.cpp
> Terrain: correctly switch blend texture after 4 layers

- RenderSystems/Direct3D11/include/OgreD3D11RenderSystem.h
- RenderSystems/Direct3D11/include/OgreD3D11Texture.h
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- RenderSystems/Direct3D11/src/OgreD3D11Texture.cpp
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
- Samples/Media/materials/programs/GLSL400/ComputeCS.glsl
- Samples/Media/materials/programs/HLSL/ComputeCS.hlsl
- Samples/Media/materials/scripts/Compute.material
- Samples/Simple/src/Compute.cpp
> D3D11: implement _dispatchCompute and UAVs

- OgreMain/include/OgreMesh.h
- OgreMain/include/OgreTangentSpaceCalc.h
- OgreMain/src/OgreMesh.cpp
- OgreMain/src/OgreTangentSpaceCalc.cpp
- Samples/DeferredShading/include/DeferredShadingDemo.h
- Samples/ShaderSystem/src/ShaderSystem.cpp
- Samples/Simple/include/Dot3Bump.h
- Samples/Simple/include/Grass.h
- Samples/Simple/include/PBR.h
- Samples/Simple/include/PNTrianglesTessellation.h
- Samples/Simple/include/Shadows.h
- Tests/VisualTests/PlayPen/src/PlayPenTests.cpp
- Tools/MeshUpgrader/src/main.cpp
> Main: drop support for putting tangents into texcoord bindings

- Docs/src/high-level-programs.md
- OgreMain/include/OgreRenderToVertexBuffer.h
- OgreMain/src/OgreRenderToVertexBuffer.cpp
- RenderSystems/Direct3D11/include/OgreD3D11RenderToVertexBuffer.h
- RenderSystems/Direct3D11/src/OgreD3D11RenderToVertexBuffer.cpp
- RenderSystems/GL/include/OgreGLRenderToVertexBuffer.h
- RenderSystems/GL/src/OgreGLRenderToVertexBuffer.cpp
- RenderSystems/GL3Plus/include/OgreGL3PlusRenderToVertexBuffer.h
- RenderSystems/GL3Plus/src/OgreGL3PlusRenderToVertexBuffer.cpp
- RenderSystems/GLES2/include/OgreGLES2RenderToVertexBuffer.h
- RenderSystems/GLES2/src/OgreGLES2RenderToVertexBuffer.cpp
- RenderSystems/GLSupport/CMakeLists.txt
- RenderSystems/GLSupport/include/OgreGLRenderToVertexBufferCommon.h
- RenderSystems/GLSupport/src/OgreGLRenderToVertexBufferCommon.cpp
- Samples/Media/materials/programs/GLSL150/ParticleGS_GenerateGS.glsl
> RenderSystems: unify RenderToVertexBuffer implementations

- Media/RTShaderLib/GLSL/SGXLib_PerPixelLighting.glsl
- OgreMain/src/OgreHardwareBufferManager.cpp
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- RenderSystems/GL/src/OgreGLRenderSystem.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
- RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
- RenderSystems/Vulkan/src/OgreVulkanRenderSystem.cpp
> GL, Vulkan, D3D11: implement VertexWinding in terms of FrontFace

- Components/RTShaderSystem/include/OgreShaderRenderState.h
- Components/RTShaderSystem/src/OgreShaderCookTorranceLighting.cpp
- Components/RTShaderSystem/src/OgreShaderExIntegratedPSSM3.cpp
- Components/RTShaderSystem/src/OgreShaderFFPLighting.cpp
- Components/RTShaderSystem/src/OgreShaderGenerator.cpp
- Components/RTShaderSystem/src/OgreShaderRenderState.cpp
- Components/RTShaderSystem/src/OgreShaderScriptTranslator.cpp
- Components/Terrain/src/OgreTerrainMaterialGeneratorA.cpp
- Samples/Common/include/Sample.h
- Samples/ShaderSystem/src/ShaderSystem.cpp
- Samples/ShaderSystemMultiLight/include/RTShaderSRSSegmentedLights.h
- Samples/ShaderSystemMultiLight/src/RTShaderSRSSegmentedLights.cpp
as we only need to know the total number of lights now
> RTSS: do not split the light count by type

- CMake/Dependencies.cmake
- CMake/Templates/project.gradle
- Components/Overlay/CMakeLists.txt
- ci-build.cmake
Update freetype, SDL and OCORNUT external libraries
> Update freetype, SDL and Android NDK

- Components/RTShaderSystem/include/OgreShaderRenderState.h
- Components/RTShaderSystem/src/OgreShaderGenerator.cpp
- Components/RTShaderSystem/src/OgreShaderRenderState.cpp
- Samples/Common/include/Sample.h
- Samples/ShaderSystem/src/ShaderSystem.cpp
- Samples/ShaderSystemMultiLight/include/ShaderSystemMultiLight.h
- Samples/ShaderSystemTexturedFog/include/ShaderSystemTexturedFog.h
- Tests/VisualTests/Common/include/VisualTest.h
this allows inspecting and modifying the active SRS
> RTSS: add default SRS first instead of last

- Components/RTShaderSystem/src/OgreShaderExNormalMapLighting.cpp
fixup for bf9613b5313d50e875edd8eae67be07c8aebbf21
> RTSS: fixup normalmap lookup

- RenderSystems/Metal/src/OgreMetalRenderSystem.mm
Fill the vendor on iOS & M1 systems with GPU_APPLE
> [Metal] Check for BCn compression on macOS Big Sur

- Docs/src/manual.md
Linking to the example, because it seems the best documentation for Ogre's ImGui integration.
> Docs: fix out-of-date Dear ImGui link

- CMake/Dependencies.cmake
Update zlib to version 1.3, correct download hash and use HTTPS instead of HTTP download URL
> Update zlib to version 1.3

- CMake/Templates/project.gradle
> android: update to AGP 7.4.2 to work with latest android studio

- Components/Overlay/include/OgreFont.h
- Components/Overlay/src/OgreFont.cpp
> Overlay: Font - handle premult alpha via antialias_colour in material

- Components/Overlay/include/OgreImGuiOverlay.h
Document the purpose of the methods OgreImGUIOverlay. Inspired by my difficulties integrating imGUI into my project.
> docs: document OgreImGUIOverlay

- CMake/toolchain/ios.toolchain.xcode.cmake
- OgreMain/include/OgreAny.h
as we got reports that it is broken on this platform
> Main: workaround any_cast on iOS by using strcmp

- RenderSystems/Direct3D11/include/OgreD3D11Prerequisites.h
- Tools/LightwaveConverter/include/lwEnvelope.h
- Tools/MayaExport/include/materialSet.h
This change fixes #2737, by removing the unnecessary checks. In the fixed lines "NULL" and "free" where changed also to "nullptr" and "delete[]".
> removed unnecessary null ptr checks 

- OgreMain/src/OgreGpuProgramParams.cpp
- RenderSystems/Direct3D11/include/OgreD3D11HLSLProgram.h
- RenderSystems/Direct3D11/src/OgreD3D11HLSLProgram.cpp
> D3D11: HLSL - give up on custom alignment logic 

- OgreMain/src/OgreSubEntity.cpp
when object space bones are in use
> Main: SubEntity - provide correct bone matrices for binding pose

- Components/Bites/CMakeLists.txt
- Components/Bites/src/OgreBitesConfigDialog.cpp
> Bites: allow force disabling native ConfigDialog

- Components/Bites/CMakeLists.txt
- Components/Bites/src/OgreApplicationContextBase.cpp
- Samples/Browser/include/SampleBrowser.h
also fix SampleBrowser
fixes #3070
> Bites: fix building without imgui

- Tools/MeshUpgrader/src/main.cpp
- Log the packing of normals and tangents
- Add option to show version
> Some enhancements for `OgreMeshUpgrader`

- PlugIns/GLSLang/src/OgreGLSLang.cpp
> GLSLang: add workaround for compilation with glslang v14+

- PlugIns/Assimp/src/AssimpLoader.cpp
> Assimp: disambiguate embedded textures

- PlugIns/Assimp/include/OgreAssimpLoader.h
- PlugIns/Assimp/src/AssimpLoader.cpp
by repeatedly applying padding
fixes #3130
> Plugins: Assimp - do not blow up aabb

- PlugIns/PCZSceneManager/src/OgrePCZSceneManager.cpp
> Fixed AntiPortals not being deleted and causing a memory leak

- PlugIns/Assimp/src/AssimpLoader.cpp
> Assimp: fix loading embedded textures in FBX

- CMake/Dependencies.cmake
> Update SDL Dependencies.cmake

- OgreMain/src/OgreRenderSystem.cpp
This reverts commit 1f61c5df47f9ea064bb686eeac39c2da67a089ac.
> Revert "Main: RenderSystem - simplifying remove render targets (#2524)"

- OgreMain/include/OgreBitwise.h
- Tests/OgreMain/src/PixelFormatTests.cpp
for correct rounding behaviour
fixes #3159
> Main: Bitwise - use floatToHalf from meshoptimizer

- OgreMain/src/OgreRenderQueueSortingGrouping.cpp
reduces asymptotic complexity and is faster
> Main: QueuedRenderableCollection - cluster instead of sorting

- Components/Overlay/include/OgreOverlay.i
> Add SWIG-template-instantiation for OverlayContainer::ChildMap

- .github/workflows/ci-build.yml
- .github/workflows/pip-build.yml
> CI: update ubuntu runners to 22.04

- Tools/AssimpConverter/CMakeLists.txt
as we use plugins.cfg nowadays
fixes #3346
> Tools: AssimpConverter - dont meddle with rpath

- Components/Terrain/src/OgreTerrainMaterialGenerator.cpp
- Docs/src/tutorials/reversed-depth.md
- OgreMain/include/OgreCommon.h
- OgreMain/include/OgreDepthBuffer.h
- OgreMain/src/OgreCompositor.cpp
- OgreMain/src/OgreCompositorInstance.cpp
- OgreMain/src/OgreRenderSystem.cpp
- OgreMain/src/OgreRenderTarget.cpp
- OgreMain/src/OgreRenderTexture.cpp
- OgreMain/src/OgreScriptTranslator.cpp
- OgreMain/src/OgreTextureShadowRenderer.cpp
- RenderSystems/Direct3D11/src/OgreD3D11RenderSystem.cpp
- RenderSystems/Direct3D9/src/OgreD3D9RenderSystem.cpp
- RenderSystems/GL/src/OgreGLRenderSystem.cpp
- RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp
- RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp
- RenderSystems/GLSupport/include/OgreGLDepthBufferCommon.h
- RenderSystems/GLSupport/src/OgreGLDepthBufferCommon.cpp
- RenderSystems/Metal/src/OgreMetalRenderSystem.mm
- RenderSystems/Tiny/src/OgreTinyRenderSystem.cpp
to move it out of class and make it more generic
> Main: replace DepthBuffer::POOL_* by RBP_* flags
